import { Eye, EyeOff, Move, RotateCcw } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Slider } from "@/components/ui/slider";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { WidgetView } from "@/components/widgets/widget-view";
import { LAYOUT_PRESETS, getWidgetLayoutBlocks, resolveWidgetLayout, type WidgetBlock, type WidgetConfig, type WidgetLayout } from "@/lib/widgets/catalog";

const ALIGNMENTS: { id: WidgetBlock["align"]; label: string }[] = [
  { id: "left", label: "Esquerda" }, { id: "center", label: "Centro" }, { id: "right", label: "Direita" },
];
const clamp = (value: number, min: number, max: number) => Math.min(max, Math.max(min, value));

function ColorField({ label, color, opacity, onColorChange, onOpacityChange }: { label: string; color: string; opacity: number; onColorChange: (value: string) => void; onOpacityChange: (value: number) => void }) {
  return <div className="space-y-2"><Label>{label}</Label><div className="flex gap-2"><Input type="color" className="h-10 w-14 shrink-0 cursor-pointer p-1" value={color} onChange={(event) => onColorChange(event.target.value)} /><Input className="h-10 font-mono uppercase" value={color} maxLength={7} onChange={(event) => onColorChange(event.target.value)} /></div><div className="flex items-center gap-3"><Slider min={0} max={100} step={1} value={[opacity]} onValueChange={([value]) => onOpacityChange(value ?? opacity)} /><span className="w-10 text-right text-xs text-muted-foreground">{opacity}%</span></div></div>;
}

/** A proportional 16:9 canvas plus a persistent, element-specific inspector. */
export function WidgetLayoutEditor({ config, onChange, layout: suppliedLayout, defaultLayout, previewConfig, title = "Layout livre" }: { config: WidgetConfig; onChange: (layout: WidgetLayout) => void; layout?: WidgetLayout; defaultLayout?: WidgetLayout; previewConfig?: WidgetConfig; title?: string }) {
  const canvasRef = useRef<HTMLDivElement>(null);
  const lotteryGameId = previewConfig?.type === "lottery" ? previewConfig.gameIds[0] : undefined;
  const blocks = getWidgetLayoutBlocks(config.type, lotteryGameId);
  const layout = suppliedLayout ?? resolveWidgetLayout(config.type, config.layout as WidgetLayout | undefined);
  const [selected, setSelected] = useState(blocks[0]?.id ?? "");
  const dragRef = useRef<{ id: string; dx: number; dy: number } | null>(null);
  const current = layout[selected];

  useEffect(() => { if (!blocks.some((block) => block.id === selected)) setSelected(blocks[0]?.id ?? ""); }, [blocks, selected]);
  function patch(id: string, next: Partial<WidgetBlock>) { const fallback = defaultLayout?.[id] ?? LAYOUT_PRESETS[config.type][id]; if (!layout[id] && !fallback) return; onChange({ ...layout, [id]: { ...fallback, ...layout[id], ...next } as WidgetBlock }); }
  function point(event: { clientX: number; clientY: number }) { const rect = canvasRef.current?.getBoundingClientRect(); return rect ? { x: ((event.clientX - rect.left) / rect.width) * 100, y: ((event.clientY - rect.top) / rect.height) * 100 } : null; }
  function startDrag(id: string, event: React.PointerEvent<HTMLDivElement>) { const block = layout[id]; const cursor = point(event); if (!block || !cursor) return; event.preventDefault(); setSelected(id); dragRef.current = { id, dx: cursor.x - block.x, dy: cursor.y - block.y }; event.currentTarget.setPointerCapture(event.pointerId); }
  function moveDrag(event: React.PointerEvent<HTMLDivElement>) { const drag = dragRef.current; const cursor = point(event); if (!drag || !cursor) return; patch(drag.id, { x: Math.round(clamp(cursor.x - drag.dx, -5, 98) * 10) / 10, y: Math.round(clamp(cursor.y - drag.dy, -5, 98) * 10) / 10 }); }

  return <section className="rounded-xl border border-border bg-card p-4"><div className="mb-4 flex items-start justify-between gap-3"><div><h3 className="text-sm font-semibold">{title}</h3><p className="text-xs text-muted-foreground">Clique ou arraste um item na prévia. A lateral edita somente o item selecionado.</p></div><Button type="button" variant="ghost" size="sm" onClick={() => onChange({ ...(defaultLayout ?? LAYOUT_PRESETS[config.type]) })}><RotateCcw className="size-4" />Padrão</Button></div>
    <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_22rem] xl:items-start"><div className="min-w-0"><div ref={canvasRef} className="relative w-full select-none overflow-hidden rounded-xl border border-border bg-black" style={{ aspectRatio: "16 / 9" }}><div className="pointer-events-none absolute inset-0"><WidgetView config={previewConfig ?? config} /></div>{blocks.map((entry) => { const block = layout[entry.id]; if (!block) return null; const active = selected === entry.id; return <div key={entry.id} role="button" tabIndex={0} aria-label={`Editar ${entry.label}`} onPointerDown={(event) => startDrag(entry.id, event)} onPointerMove={moveDrag} onPointerUp={() => { dragRef.current = null; }} onPointerCancel={() => { dragRef.current = null; }} onClick={() => setSelected(entry.id)} className={`absolute cursor-move rounded-md border-2 border-dashed ${active ? "border-primary bg-primary/15" : "border-primary/40 bg-primary/5 hover:border-primary"} ${block.hidden ? "opacity-40" : ""}`} style={{ left: `${block.x}%`, top: `${block.y}%`, width: `${block.w}%`, height: `${clamp(block.size * 1.5, 4, 60)}%`, touchAction: "none" }}><span className="absolute -top-0.5 left-1 flex items-center gap-1 whitespace-nowrap text-[10px] font-medium text-primary"><Move className="size-3" />{entry.label}</span></div>; })}</div><div className="mt-3 flex max-h-24 flex-wrap gap-2 overflow-y-auto pr-1">{blocks.map((entry) => <Button key={entry.id} type="button" size="sm" variant={selected === entry.id ? "default" : "outline"} onClick={() => setSelected(entry.id)}>{entry.label}</Button>)}</div></div>
      {current ? <aside className="rounded-xl border border-border bg-background xl:sticky xl:top-4 xl:max-h-[calc(100vh-2rem)] xl:overflow-y-auto"><div className="border-b border-border p-4"><p className="text-xs text-muted-foreground">Editando item</p><h4 className="font-semibold">{blocks.find((block) => block.id === selected)?.label}</h4></div><div className="space-y-5 p-4"><div className="space-y-4"><div className="space-y-2"><Label>Tamanho: {current.size.toFixed(1)}% da altura</Label><Slider min={0.8} max={34} step={0.2} value={[current.size]} onValueChange={([value]) => patch(selected, { size: value ?? current.size })} /></div><div className="space-y-2"><Label>Largura: {Math.round(current.w)}%</Label><Slider min={5} max={100} step={1} value={[current.w]} onValueChange={([value]) => patch(selected, { w: value ?? current.w })} /></div><div className="grid grid-cols-2 gap-3"><div className="space-y-2"><Label>Horizontal: {current.x.toFixed(1)}%</Label><Slider min={-5} max={98} step={0.5} value={[current.x]} onValueChange={([value]) => patch(selected, { x: value ?? current.x })} /></div><div className="space-y-2"><Label>Vertical: {current.y.toFixed(1)}%</Label><Slider min={-5} max={98} step={0.5} value={[current.y]} onValueChange={([value]) => patch(selected, { y: value ?? current.y })} /></div></div></div><ColorField label="Cor do texto" color={current.color || "#FFFFFF"} opacity={current.colorOpacity} onColorChange={(color) => patch(selected, { color })} onOpacityChange={(colorOpacity) => patch(selected, { colorOpacity })} /><div className="space-y-2"><Label>Alinhamento</Label><div className="grid grid-cols-3 gap-2">{ALIGNMENTS.map((option) => <Button key={option.id} type="button" size="sm" variant={current.align === option.id ? "default" : "outline"} onClick={() => patch(selected, { align: option.id })}>{option.label}</Button>)}</div></div><Button type="button" className="w-full" variant="outline" onClick={() => patch(selected, { hidden: !current.hidden })}>{current.hidden ? <EyeOff className="size-4" /> : <Eye className="size-4" />}{current.hidden ? "Mostrar item" : "Ocultar item"}</Button>
        <details className="rounded-lg border border-border" open><summary className="cursor-pointer px-3 py-2 text-sm font-medium">Fundo do item</summary><div className="space-y-4 border-t border-border p-3"><Select value={current.backgroundMode === "transparent" ? "solid" : current.backgroundMode} onValueChange={(backgroundMode) => patch(selected, { backgroundMode: backgroundMode as WidgetBlock["backgroundMode"] })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="solid">Cor sólida</SelectItem><SelectItem value="gradient">Degradê</SelectItem><SelectItem value="image">Imagem</SelectItem></SelectContent></Select><ColorField label="Cor sólida" color={current.backgroundColor || "#000000"} opacity={current.backgroundColorOpacity} onColorChange={(backgroundColor) => patch(selected, { backgroundColor, backgroundMode: "solid" })} onOpacityChange={(backgroundColorOpacity) => patch(selected, { backgroundColorOpacity })} />{current.backgroundMode === "image" ? <Input placeholder="URL HTTPS da imagem" value={current.backgroundImageUrl} onChange={(event) => patch(selected, { backgroundImageUrl: event.target.value })} /> : null}</div></details>
        <details className="rounded-lg border border-border"><summary className="cursor-pointer px-3 py-2 text-sm font-medium">Gradiente e sobreposição</summary><div className="space-y-4 border-t border-border p-3"><ColorField label="Início do gradiente" color={current.backgroundGradientFrom} opacity={current.backgroundGradientFromOpacity} onColorChange={(backgroundGradientFrom) => patch(selected, { backgroundGradientFrom, backgroundMode: "gradient" })} onOpacityChange={(backgroundGradientFromOpacity) => patch(selected, { backgroundGradientFromOpacity })} /><ColorField label="Fim do gradiente" color={current.backgroundGradientTo} opacity={current.backgroundGradientToOpacity} onColorChange={(backgroundGradientTo) => patch(selected, { backgroundGradientTo, backgroundMode: "gradient" })} onOpacityChange={(backgroundGradientToOpacity) => patch(selected, { backgroundGradientToOpacity })} /><div className="space-y-2"><Label>Ângulo: {current.backgroundGradientAngle}°</Label><Slider min={0} max={360} step={1} value={[current.backgroundGradientAngle]} onValueChange={([value]) => patch(selected, { backgroundGradientAngle: value ?? 160 })} /></div>{current.backgroundImageUrl ? <><Select value={current.imageOverlayMode} onValueChange={(imageOverlayMode) => patch(selected, { imageOverlayMode: imageOverlayMode as WidgetBlock["imageOverlayMode"] })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="none">Sem sobreposição</SelectItem><SelectItem value="solid">Cor sólida</SelectItem><SelectItem value="gradient">Degradê</SelectItem></SelectContent></Select>{current.imageOverlayMode === "solid" ? <ColorField label="Sobreposição" color={current.imageOverlayColor} opacity={current.imageOverlayOpacity} onColorChange={(imageOverlayColor) => patch(selected, { imageOverlayColor })} onOpacityChange={(imageOverlayOpacity) => patch(selected, { imageOverlayOpacity })} /> : null}</> : null}</div></details>
      </div></aside> : null}</div></section>;
}
