import { Copy, Eye, EyeOff, Move, RotateCcw } from "lucide-react";
import { useEffect, useRef, useState } from "react";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { WidgetView } from "@/components/widgets/widget-view";
import { LAYOUT_PRESETS, getWidgetLayoutBlocks, resolveWidgetLayout, type WidgetBlock, type WidgetConfig, type WidgetLayout } from "@/lib/widgets/catalog";

const ALIGNMENTS: { id: WidgetBlock["align"]; label: string }[] = [
  { id: "left", label: "Esquerda" }, { id: "center", label: "Centro" }, { id: "right", label: "Direita" },
];
const clamp = (value: number, min: number, max: number) => Math.min(max, Math.max(min, value));

function NumberField({ label, value, min, max, step = 0.1, suffix = "%", onChange }: { label: string; value: number; min: number; max: number; step?: number; suffix?: string; onChange: (value: number) => void }) {
  return <div className="space-y-1"><Label className="text-xs">{label}</Label><div className="flex items-center gap-2"><Input type="number" min={min} max={max} step={step} className="h-9" value={value} onChange={(event) => { const next = Number(event.target.value); if (Number.isFinite(next)) onChange(clamp(next, min, max)); }} /><span className="text-xs text-muted-foreground">{suffix}</span></div></div>;
}
function ColorField({ label, color, opacity, onColorChange, onOpacityChange }: { label: string; color: string; opacity: number; onColorChange: (value: string) => void; onOpacityChange: (value: number) => void }) {
  return <div className="space-y-2"><Label>{label}</Label><div className="flex gap-2"><Input type="color" className="h-10 w-14 shrink-0 cursor-pointer p-1" value={color} onChange={(event) => onColorChange(event.target.value)} /><Input className="h-10 font-mono uppercase" value={color} maxLength={7} onChange={(event) => onColorChange(event.target.value)} /></div><NumberField label="Opacidade" value={opacity} min={0} max={100} step={1} onChange={onOpacityChange} /></div>;
}

/** 16:9 WYSIWYG canvas with Elementor-style multi-selection and inspector. */
export function WidgetLayoutEditor({ config, onChange, layout: suppliedLayout, defaultLayout, previewConfig, title = "Layout livre" }: { config: WidgetConfig; onChange: (layout: WidgetLayout) => void; layout?: WidgetLayout; defaultLayout?: WidgetLayout; previewConfig?: WidgetConfig; title?: string }) {
  const canvasRef = useRef<HTMLDivElement>(null);
  const lotteryGameId = previewConfig?.type === "lottery" ? previewConfig.gameIds[0] : undefined;
  const blocks = getWidgetLayoutBlocks(config.type, lotteryGameId);
  const layout = suppliedLayout ?? resolveWidgetLayout(config.type, config.layout as WidgetLayout | undefined);
  const [selectedIds, setSelectedIds] = useState<string[]>([blocks[0]?.id ?? ""]);
  const [referenceId, setReferenceId] = useState(blocks[0]?.id ?? "");
  const dragRef = useRef<{ id: string; startX: number; startY: number; positions: Record<string, { x: number; y: number }> } | null>(null);
  const current = layout[referenceId];

  useEffect(() => { const valid = selectedIds.filter((id) => blocks.some((block) => block.id === id)); const initial = valid.length ? valid : [blocks[0]?.id ?? ""]; if (initial.length !== selectedIds.length) setSelectedIds(initial); if (!initial.includes(referenceId)) setReferenceId(initial[0] ?? ""); }, [blocks, referenceId, selectedIds]);
  function patch(id: string, next: Partial<WidgetBlock>) { const fallback = defaultLayout?.[id] ?? LAYOUT_PRESETS[config.type][id]; if (!layout[id] && !fallback) return; onChange({ ...layout, [id]: { ...fallback, ...layout[id], ...next } as WidgetBlock }); }
  function patchMany(next: Record<string, Partial<WidgetBlock>>) { const merged = { ...layout }; for (const [id, patchValue] of Object.entries(next)) { const fallback = defaultLayout?.[id] ?? LAYOUT_PRESETS[config.type][id]; if (merged[id] || fallback) merged[id] = { ...fallback, ...merged[id], ...patchValue } as WidgetBlock; } onChange(merged); }
  function point(event: { clientX: number; clientY: number }) { const rect = canvasRef.current?.getBoundingClientRect(); return rect ? { x: ((event.clientX - rect.left) / rect.width) * 100, y: ((event.clientY - rect.top) / rect.height) * 100 } : null; }
  function select(id: string, shiftKey = false) { if (shiftKey) { setSelectedIds((currentIds) => currentIds.includes(id) ? currentIds.filter((entry) => entry !== id) : [...currentIds, id]); return; } if (selectedIds.includes(id) && selectedIds.length > 1) { setReferenceId(id); return; } setSelectedIds([id]); setReferenceId(id); }
  function startDrag(id: string, event: React.PointerEvent<HTMLDivElement>) { const cursor = point(event); if (!cursor || !layout[id]) return; event.preventDefault(); select(id, event.shiftKey); const ids = event.shiftKey ? (selectedIds.includes(id) ? selectedIds : [...selectedIds, id]) : selectedIds.includes(id) ? selectedIds : [id]; const positions = Object.fromEntries(ids.filter((entry) => layout[entry]).map((entry) => [entry, { x: layout[entry]!.x, y: layout[entry]!.y }])); dragRef.current = { id, startX: cursor.x, startY: cursor.y, positions }; event.currentTarget.setPointerCapture(event.pointerId); }
  function moveDrag(event: React.PointerEvent<HTMLDivElement>) { const drag = dragRef.current; const cursor = point(event); if (!drag || !cursor) return; const deltaX = cursor.x - drag.startX; const deltaY = cursor.y - drag.startY; patchMany(Object.fromEntries(Object.entries(drag.positions).map(([id, position]) => [id, { x: Math.round(clamp(position.x + deltaX, -5, 98) * 10) / 10, y: Math.round(clamp(position.y + deltaY, -5, 98) * 10) / 10 }]))); }
  function copyStyle() { if (!current) return; const { x: _x, y: _y, w: _w, hidden: _hidden, ...style } = current; patchMany(Object.fromEntries(selectedIds.filter((id) => id !== referenceId).map((id) => [id, style]))); }
  function alignLeft() { if (!current) return; patchMany(Object.fromEntries(selectedIds.filter((id) => id !== referenceId).map((id) => [id, { x: current.x }]))); }
  function alignRight() { if (!current) return; patchMany(Object.fromEntries(selectedIds.filter((id) => id !== referenceId).map((id) => [id, { x: clamp(current.x + current.w - (layout[id]?.w ?? 0), -5, 98) }]))); }

  return <section className="rounded-xl border border-border bg-card p-4"><div className="mb-4 flex items-start justify-between gap-3"><div><h3 className="text-sm font-semibold">{title}</h3><p className="text-xs text-muted-foreground">Arraste elementos. Use Shift para selecionar vários e clique por último no item de referência.</p></div><Button type="button" variant="ghost" size="sm" onClick={() => onChange({ ...(defaultLayout ?? LAYOUT_PRESETS[config.type]) })}><RotateCcw className="size-4" />Padrão</Button></div>
    <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_22rem] xl:items-start"><div className="min-w-0"><div ref={canvasRef} className="relative w-full select-none overflow-hidden rounded-xl border border-border bg-black" style={{ aspectRatio: "16 / 9" }}><div className="pointer-events-none absolute inset-0"><WidgetView config={previewConfig ?? config} /></div>{blocks.map((entry) => { const block = layout[entry.id]; if (!block) return null; const selected = selectedIds.includes(entry.id); const reference = referenceId === entry.id; return <div key={entry.id} role="button" tabIndex={0} aria-label={`Editar ${entry.label}`} onPointerDown={(event) => startDrag(entry.id, event)} onPointerMove={moveDrag} onPointerUp={() => { dragRef.current = null; }} onPointerCancel={() => { dragRef.current = null; }} onClick={(event) => select(entry.id, event.shiftKey)} className={`absolute cursor-move rounded-md border-2 border-dashed ${reference ? "border-primary bg-primary/20" : selected ? "border-cyan-300 bg-cyan-300/10" : "border-primary/40 bg-primary/5 hover:border-primary"} ${block.hidden ? "opacity-40" : ""}`} style={{ left: `${block.x}%`, top: `${block.y}%`, width: `${block.w}%`, height: `${clamp(block.size * 1.5, 4, 60)}%`, touchAction: "none" }}><span className="absolute -top-0.5 left-1 flex items-center gap-1 whitespace-nowrap text-[10px] font-medium text-primary"><Move className="size-3" />{entry.label}{reference ? " • referência" : ""}</span></div>; })}</div><div className="mt-3 flex max-h-24 flex-wrap gap-2 overflow-y-auto pr-1">{blocks.map((entry) => <Button key={entry.id} type="button" size="sm" variant={referenceId === entry.id ? "default" : selectedIds.includes(entry.id) ? "secondary" : "outline"} onClick={(event) => select(entry.id, event.shiftKey)}>{entry.label}</Button>)}</div></div>
      {current ? <aside className="rounded-xl border border-border bg-background xl:sticky xl:top-4 xl:max-h-[calc(100vh-2rem)] xl:overflow-y-auto"><div className="border-b border-border p-4"><p className="text-xs text-muted-foreground">Referência · {selectedIds.length} selecionado(s)</p><h4 className="font-semibold">{blocks.find((block) => block.id === referenceId)?.label}</h4></div><div className="space-y-5 p-4"><div className="grid grid-cols-2 gap-3"><NumberField label="Fonte" value={current.size} min={0.8} max={34} onChange={(size) => patch(referenceId, { size })} /><NumberField label="Largura" value={current.w} min={5} max={100} step={1} onChange={(w) => patch(referenceId, { w })} /><NumberField label="Esquerda" value={current.x} min={-5} max={98} onChange={(x) => patch(referenceId, { x })} /><NumberField label="Topo" value={current.y} min={-5} max={98} onChange={(y) => patch(referenceId, { y })} /></div><ColorField label="Cor do texto" color={current.color || "#FFFFFF"} opacity={current.colorOpacity} onColorChange={(color) => patch(referenceId, { color })} onOpacityChange={(colorOpacity) => patch(referenceId, { colorOpacity })} /><div className="space-y-2"><Label>Alinhamento interno</Label><div className="grid grid-cols-3 gap-2">{ALIGNMENTS.map((option) => <Button key={option.id} type="button" size="sm" variant={current.align === option.id ? "default" : "outline"} onClick={() => patch(referenceId, { align: option.id })}>{option.label}</Button>)}</div></div>{selectedIds.length > 1 ? <div className="space-y-2 rounded-lg border border-primary/40 bg-primary/5 p-3"><p className="text-xs font-medium">Ações para a seleção</p><Button type="button" className="w-full" size="sm" onClick={copyStyle}><Copy className="size-4" />Aplicar estilo da referência</Button><div className="grid grid-cols-2 gap-2"><Button type="button" variant="outline" size="sm" onClick={alignLeft}>Alinhar vertical<br />margem esquerda</Button><Button type="button" variant="outline" size="sm" onClick={alignRight}>Alinhar horizontal<br />margem direita</Button></div></div> : null}<Button type="button" className="w-full" variant="outline" onClick={() => patch(referenceId, { hidden: !current.hidden })}>{current.hidden ? <EyeOff className="size-4" /> : <Eye className="size-4" />}{current.hidden ? "Mostrar item" : "Ocultar item"}</Button>
        <details className="rounded-lg border border-border" open><summary className="cursor-pointer px-3 py-2 text-sm font-medium">Fundo do item</summary><div className="space-y-4 border-t border-border p-3"><Select value={current.backgroundMode === "transparent" ? "solid" : current.backgroundMode} onValueChange={(backgroundMode) => patch(referenceId, { backgroundMode: backgroundMode as WidgetBlock["backgroundMode"] })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="solid">Cor sólida</SelectItem><SelectItem value="gradient">Degradê</SelectItem><SelectItem value="image">Imagem</SelectItem></SelectContent></Select><ColorField label="Cor sólida" color={current.backgroundColor || "#000000"} opacity={current.backgroundColorOpacity} onColorChange={(backgroundColor) => patch(referenceId, { backgroundColor, backgroundMode: "solid" })} onOpacityChange={(backgroundColorOpacity) => patch(referenceId, { backgroundColorOpacity })} />{current.backgroundMode === "image" ? <Input placeholder="URL HTTPS da imagem" value={current.backgroundImageUrl} onChange={(event) => patch(referenceId, { backgroundImageUrl: event.target.value })} /> : null}</div></details>
        <details className="rounded-lg border border-border"><summary className="cursor-pointer px-3 py-2 text-sm font-medium">Gradiente e sobreposição</summary><div className="space-y-4 border-t border-border p-3"><ColorField label="Início do gradiente" color={current.backgroundGradientFrom} opacity={current.backgroundGradientFromOpacity} onColorChange={(backgroundGradientFrom) => patch(referenceId, { backgroundGradientFrom, backgroundMode: "gradient" })} onOpacityChange={(backgroundGradientFromOpacity) => patch(referenceId, { backgroundGradientFromOpacity })} /><ColorField label="Fim do gradiente" color={current.backgroundGradientTo} opacity={current.backgroundGradientToOpacity} onColorChange={(backgroundGradientTo) => patch(referenceId, { backgroundGradientTo, backgroundMode: "gradient" })} onOpacityChange={(backgroundGradientToOpacity) => patch(referenceId, { backgroundGradientToOpacity })} /><NumberField label="Ângulo" value={current.backgroundGradientAngle} min={0} max={360} step={1} suffix="°" onChange={(backgroundGradientAngle) => patch(referenceId, { backgroundGradientAngle })} />{current.backgroundImageUrl ? <><Select value={current.imageOverlayMode} onValueChange={(imageOverlayMode) => patch(referenceId, { imageOverlayMode: imageOverlayMode as WidgetBlock["imageOverlayMode"] })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="none">Sem sobreposição</SelectItem><SelectItem value="solid">Cor sólida</SelectItem><SelectItem value="gradient">Degradê</SelectItem></SelectContent></Select>{current.imageOverlayMode === "solid" ? <ColorField label="Sobreposição" color={current.imageOverlayColor} opacity={current.imageOverlayOpacity} onColorChange={(imageOverlayColor) => patch(referenceId, { imageOverlayColor })} onOpacityChange={(imageOverlayOpacity) => patch(referenceId, { imageOverlayOpacity })} /> : null}</> : null}</div></details>
      </div></aside> : null}</div></section>;
}
