/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as SenhasRouteImport } from './routes/senhas'
import { Route as StudioRouteRouteImport } from './routes/studio/route'
import { Route as TelaRouteImport } from './routes/tela'
import { Route as TorreRouteRouteImport } from './routes/torre/route'
import { Route as StudioIndexRouteImport } from './routes/studio/index'
import { Route as StudioAgendaRouteImport } from './routes/studio/agenda'
import { Route as StudioConfiguracoesRouteImport } from './routes/studio/configuracoes'
import { Route as StudioConteudosRouteImport } from './routes/studio/conteudos'
import { Route as StudioPlaylistsRouteImport } from './routes/studio/playlists'
import { Route as StudioRelatoriosRouteImport } from './routes/studio/relatorios'
import { Route as StudioSenhasRouteImport } from './routes/studio/senhas'
import { Route as StudioTelasRouteImport } from './routes/studio/telas'
import { Route as TorreIndexRouteImport } from './routes/torre/index'
import { Route as TorrePlanosRouteImport } from './routes/torre/planos'
import { Route as ApiBrandingLogoRouteImport } from './routes/api/branding/logo'
import { Route as ApiMediaUploadRouteImport } from './routes/api/media/upload'
import { Route as ApiPublicWidgetDataRouteImport } from './routes/api/public/widget-data'
import { Route as TorreClientesIndexRouteImport } from './routes/torre/clientes/index'
import { Route as TorreClientesOrganizationIdRouteImport } from './routes/torre/clientes/$organizationId'
import { Route as ApiPublicPlayerEventsRouteImport } from './routes/api/public/player/events'
import { Route as ApiPublicPlayerPlaybackRouteImport } from './routes/api/public/player/playback'
import { Route as ApiPublicPlayerRegisterRouteImport } from './routes/api/public/player/register'
import { Route as ApiPublicPlayerStatusRouteImport } from './routes/api/public/player/status'
import { Route as ApiPublicPlayerSyncRouteImport } from './routes/api/public/player/sync'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const SenhasRoute = SenhasRouteImport.update({
  id: '/senhas',
  path: '/senhas',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRouteRoute = StudioRouteRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const TelaRoute = TelaRouteImport.update({
  id: '/tela',
  path: '/tela',
  getParentRoute: () => rootRouteImport,
} as any)
const TorreRouteRoute = TorreRouteRouteImport.update({
  id: '/torre',
  path: '/torre',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRouteRoute,
} as any)
const StudioAgendaRoute = StudioAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => StudioRouteRoute,
} as any)
const StudioConfiguracoesRoute = StudioConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => StudioRouteRoute,
} as any)
const StudioConteudosRoute = StudioConteudosRouteImport.update({
  id: '/conteudos',
  path: '/conteudos',
  getParentRoute: () => StudioRouteRoute,
} as any)
const StudioPlaylistsRoute = StudioPlaylistsRouteImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => StudioRouteRoute,
} as any)
const StudioRelatoriosRoute = StudioRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => StudioRouteRoute,
} as any)
const StudioSenhasRoute = StudioSenhasRouteImport.update({
  id: '/senhas',
  path: '/senhas',
  getParentRoute: () => StudioRouteRoute,
} as any)
const StudioTelasRoute = StudioTelasRouteImport.update({
  id: '/telas',
  path: '/telas',
  getParentRoute: () => StudioRouteRoute,
} as any)
const TorreIndexRoute = TorreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TorreRouteRoute,
} as any)
const TorrePlanosRoute = TorrePlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => TorreRouteRoute,
} as any)
const ApiBrandingLogoRoute = ApiBrandingLogoRouteImport.update({
  id: '/api/branding/logo',
  path: '/api/branding/logo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaUploadRoute = ApiMediaUploadRouteImport.update({
  id: '/api/media/upload',
  path: '/api/media/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWidgetDataRoute = ApiPublicWidgetDataRouteImport.update({
  id: '/api/public/widget-data',
  path: '/api/public/widget-data',
  getParentRoute: () => rootRouteImport,
} as any)
const TorreClientesIndexRoute = TorreClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => TorreRouteRoute,
} as any)
const TorreClientesOrganizationIdRoute =
  TorreClientesOrganizationIdRouteImport.update({
    id: '/clientes/$organizationId',
    path: '/clientes/$organizationId',
    getParentRoute: () => TorreRouteRoute,
  } as any)
const ApiPublicPlayerEventsRoute = ApiPublicPlayerEventsRouteImport.update({
  id: '/api/public/player/events',
  path: '/api/public/player/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPlayerPlaybackRoute = ApiPublicPlayerPlaybackRouteImport.update({
  id: '/api/public/player/playback',
  path: '/api/public/player/playback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPlayerRegisterRoute = ApiPublicPlayerRegisterRouteImport.update({
  id: '/api/public/player/register',
  path: '/api/public/player/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPlayerStatusRoute = ApiPublicPlayerStatusRouteImport.update({
  id: '/api/public/player/status',
  path: '/api/public/player/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPlayerSyncRoute = ApiPublicPlayerSyncRouteImport.update({
  id: '/api/public/player/sync',
  path: '/api/public/player/sync',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/studio': typeof StudioRouteRouteWithChildren
  '/torre': typeof TorreRouteRouteWithChildren
  '/entrar': typeof EntrarRoute
  '/senhas': typeof SenhasRoute
  '/tela': typeof TelaRoute
  '/studio/agenda': typeof StudioAgendaRoute
  '/studio/configuracoes': typeof StudioConfiguracoesRoute
  '/studio/conteudos': typeof StudioConteudosRoute
  '/studio/playlists': typeof StudioPlaylistsRoute
  '/studio/relatorios': typeof StudioRelatoriosRoute
  '/studio/senhas': typeof StudioSenhasRoute
  '/studio/telas': typeof StudioTelasRoute
  '/torre/planos': typeof TorrePlanosRoute
  '/studio/': typeof StudioIndexRoute
  '/torre/': typeof TorreIndexRoute
  '/api/branding/logo': typeof ApiBrandingLogoRoute
  '/api/media/upload': typeof ApiMediaUploadRoute
  '/api/public/widget-data': typeof ApiPublicWidgetDataRoute
  '/torre/clientes/$organizationId': typeof TorreClientesOrganizationIdRoute
  '/torre/clientes/': typeof TorreClientesIndexRoute
  '/api/public/player/events': typeof ApiPublicPlayerEventsRoute
  '/api/public/player/playback': typeof ApiPublicPlayerPlaybackRoute
  '/api/public/player/register': typeof ApiPublicPlayerRegisterRoute
  '/api/public/player/status': typeof ApiPublicPlayerStatusRoute
  '/api/public/player/sync': typeof ApiPublicPlayerSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/senhas': typeof SenhasRoute
  '/tela': typeof TelaRoute
  '/studio/agenda': typeof StudioAgendaRoute
  '/studio/configuracoes': typeof StudioConfiguracoesRoute
  '/studio/conteudos': typeof StudioConteudosRoute
  '/studio/playlists': typeof StudioPlaylistsRoute
  '/studio/relatorios': typeof StudioRelatoriosRoute
  '/studio/senhas': typeof StudioSenhasRoute
  '/studio/telas': typeof StudioTelasRoute
  '/torre/planos': typeof TorrePlanosRoute
  '/studio': typeof StudioIndexRoute
  '/torre': typeof TorreIndexRoute
  '/api/branding/logo': typeof ApiBrandingLogoRoute
  '/api/media/upload': typeof ApiMediaUploadRoute
  '/api/public/widget-data': typeof ApiPublicWidgetDataRoute
  '/torre/clientes/$organizationId': typeof TorreClientesOrganizationIdRoute
  '/torre/clientes': typeof TorreClientesIndexRoute
  '/api/public/player/events': typeof ApiPublicPlayerEventsRoute
  '/api/public/player/playback': typeof ApiPublicPlayerPlaybackRoute
  '/api/public/player/register': typeof ApiPublicPlayerRegisterRoute
  '/api/public/player/status': typeof ApiPublicPlayerStatusRoute
  '/api/public/player/sync': typeof ApiPublicPlayerSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/studio': typeof StudioRouteRouteWithChildren
  '/torre': typeof TorreRouteRouteWithChildren
  '/entrar': typeof EntrarRoute
  '/senhas': typeof SenhasRoute
  '/tela': typeof TelaRoute
  '/studio/agenda': typeof StudioAgendaRoute
  '/studio/configuracoes': typeof StudioConfiguracoesRoute
  '/studio/conteudos': typeof StudioConteudosRoute
  '/studio/playlists': typeof StudioPlaylistsRoute
  '/studio/relatorios': typeof StudioRelatoriosRoute
  '/studio/senhas': typeof StudioSenhasRoute
  '/studio/telas': typeof StudioTelasRoute
  '/torre/planos': typeof TorrePlanosRoute
  '/studio/': typeof StudioIndexRoute
  '/torre/': typeof TorreIndexRoute
  '/api/branding/logo': typeof ApiBrandingLogoRoute
  '/api/media/upload': typeof ApiMediaUploadRoute
  '/api/public/widget-data': typeof ApiPublicWidgetDataRoute
  '/torre/clientes/$organizationId': typeof TorreClientesOrganizationIdRoute
  '/torre/clientes/': typeof TorreClientesIndexRoute
  '/api/public/player/events': typeof ApiPublicPlayerEventsRoute
  '/api/public/player/playback': typeof ApiPublicPlayerPlaybackRoute
  '/api/public/player/register': typeof ApiPublicPlayerRegisterRoute
  '/api/public/player/status': typeof ApiPublicPlayerStatusRoute
  '/api/public/player/sync': typeof ApiPublicPlayerSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/studio'
    | '/torre'
    | '/entrar'
    | '/senhas'
    | '/tela'
    | '/studio/agenda'
    | '/studio/configuracoes'
    | '/studio/conteudos'
    | '/studio/playlists'
    | '/studio/relatorios'
    | '/studio/senhas'
    | '/studio/telas'
    | '/torre/planos'
    | '/studio/'
    | '/torre/'
    | '/api/branding/logo'
    | '/api/media/upload'
    | '/api/public/widget-data'
    | '/torre/clientes/$organizationId'
    | '/torre/clientes/'
    | '/api/public/player/events'
    | '/api/public/player/playback'
    | '/api/public/player/register'
    | '/api/public/player/status'
    | '/api/public/player/sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/entrar'
    | '/senhas'
    | '/tela'
    | '/studio/agenda'
    | '/studio/configuracoes'
    | '/studio/conteudos'
    | '/studio/playlists'
    | '/studio/relatorios'
    | '/studio/senhas'
    | '/studio/telas'
    | '/torre/planos'
    | '/studio'
    | '/torre'
    | '/api/branding/logo'
    | '/api/media/upload'
    | '/api/public/widget-data'
    | '/torre/clientes/$organizationId'
    | '/torre/clientes'
    | '/api/public/player/events'
    | '/api/public/player/playback'
    | '/api/public/player/register'
    | '/api/public/player/status'
    | '/api/public/player/sync'
  id:
    | '__root__'
    | '/'
    | '/studio'
    | '/torre'
    | '/entrar'
    | '/senhas'
    | '/tela'
    | '/studio/agenda'
    | '/studio/configuracoes'
    | '/studio/conteudos'
    | '/studio/playlists'
    | '/studio/relatorios'
    | '/studio/senhas'
    | '/studio/telas'
    | '/torre/planos'
    | '/studio/'
    | '/torre/'
    | '/api/branding/logo'
    | '/api/media/upload'
    | '/api/public/widget-data'
    | '/torre/clientes/$organizationId'
    | '/torre/clientes/'
    | '/api/public/player/events'
    | '/api/public/player/playback'
    | '/api/public/player/register'
    | '/api/public/player/status'
    | '/api/public/player/sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StudioRouteRoute: typeof StudioRouteRouteWithChildren
  TorreRouteRoute: typeof TorreRouteRouteWithChildren
  EntrarRoute: typeof EntrarRoute
  SenhasRoute: typeof SenhasRoute
  TelaRoute: typeof TelaRoute
  ApiBrandingLogoRoute: typeof ApiBrandingLogoRoute
  ApiMediaUploadRoute: typeof ApiMediaUploadRoute
  ApiPublicWidgetDataRoute: typeof ApiPublicWidgetDataRoute
  ApiPublicPlayerEventsRoute: typeof ApiPublicPlayerEventsRoute
  ApiPublicPlayerPlaybackRoute: typeof ApiPublicPlayerPlaybackRoute
  ApiPublicPlayerRegisterRoute: typeof ApiPublicPlayerRegisterRoute
  ApiPublicPlayerStatusRoute: typeof ApiPublicPlayerStatusRoute
  ApiPublicPlayerSyncRoute: typeof ApiPublicPlayerSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/senhas': {
      id: '/senhas'
      path: '/senhas'
      fullPath: '/senhas'
      preLoaderRoute: typeof SenhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tela': {
      id: '/tela'
      path: '/tela'
      fullPath: '/tela'
      preLoaderRoute: typeof TelaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/torre': {
      id: '/torre'
      path: '/torre'
      fullPath: '/torre'
      preLoaderRoute: typeof TorreRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/studio/agenda': {
      id: '/studio/agenda'
      path: '/agenda'
      fullPath: '/studio/agenda'
      preLoaderRoute: typeof StudioAgendaRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/studio/configuracoes': {
      id: '/studio/configuracoes'
      path: '/configuracoes'
      fullPath: '/studio/configuracoes'
      preLoaderRoute: typeof StudioConfiguracoesRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/studio/conteudos': {
      id: '/studio/conteudos'
      path: '/conteudos'
      fullPath: '/studio/conteudos'
      preLoaderRoute: typeof StudioConteudosRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/studio/playlists': {
      id: '/studio/playlists'
      path: '/playlists'
      fullPath: '/studio/playlists'
      preLoaderRoute: typeof StudioPlaylistsRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/studio/relatorios': {
      id: '/studio/relatorios'
      path: '/relatorios'
      fullPath: '/studio/relatorios'
      preLoaderRoute: typeof StudioRelatoriosRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/studio/senhas': {
      id: '/studio/senhas'
      path: '/senhas'
      fullPath: '/studio/senhas'
      preLoaderRoute: typeof StudioSenhasRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/studio/telas': {
      id: '/studio/telas'
      path: '/telas'
      fullPath: '/studio/telas'
      preLoaderRoute: typeof StudioTelasRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/torre/': {
      id: '/torre/'
      path: '/'
      fullPath: '/torre/'
      preLoaderRoute: typeof TorreIndexRouteImport
      parentRoute: typeof TorreRouteRoute
    }
    '/torre/planos': {
      id: '/torre/planos'
      path: '/planos'
      fullPath: '/torre/planos'
      preLoaderRoute: typeof TorrePlanosRouteImport
      parentRoute: typeof TorreRouteRoute
    }
    '/api/branding/logo': {
      id: '/api/branding/logo'
      path: '/api/branding/logo'
      fullPath: '/api/branding/logo'
      preLoaderRoute: typeof ApiBrandingLogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/upload': {
      id: '/api/media/upload'
      path: '/api/media/upload'
      fullPath: '/api/media/upload'
      preLoaderRoute: typeof ApiMediaUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/widget-data': {
      id: '/api/public/widget-data'
      path: '/api/public/widget-data'
      fullPath: '/api/public/widget-data'
      preLoaderRoute: typeof ApiPublicWidgetDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/torre/clientes/': {
      id: '/torre/clientes/'
      path: '/clientes'
      fullPath: '/torre/clientes/'
      preLoaderRoute: typeof TorreClientesIndexRouteImport
      parentRoute: typeof TorreRouteRoute
    }
    '/torre/clientes/$organizationId': {
      id: '/torre/clientes/$organizationId'
      path: '/clientes/$organizationId'
      fullPath: '/torre/clientes/$organizationId'
      preLoaderRoute: typeof TorreClientesOrganizationIdRouteImport
      parentRoute: typeof TorreRouteRoute
    }
    '/api/public/player/events': {
      id: '/api/public/player/events'
      path: '/api/public/player/events'
      fullPath: '/api/public/player/events'
      preLoaderRoute: typeof ApiPublicPlayerEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/player/playback': {
      id: '/api/public/player/playback'
      path: '/api/public/player/playback'
      fullPath: '/api/public/player/playback'
      preLoaderRoute: typeof ApiPublicPlayerPlaybackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/player/register': {
      id: '/api/public/player/register'
      path: '/api/public/player/register'
      fullPath: '/api/public/player/register'
      preLoaderRoute: typeof ApiPublicPlayerRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/player/status': {
      id: '/api/public/player/status'
      path: '/api/public/player/status'
      fullPath: '/api/public/player/status'
      preLoaderRoute: typeof ApiPublicPlayerStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/player/sync': {
      id: '/api/public/player/sync'
      path: '/api/public/player/sync'
      fullPath: '/api/public/player/sync'
      preLoaderRoute: typeof ApiPublicPlayerSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StudioRouteRouteChildren {
  StudioAgendaRoute: typeof StudioAgendaRoute
  StudioConfiguracoesRoute: typeof StudioConfiguracoesRoute
  StudioConteudosRoute: typeof StudioConteudosRoute
  StudioPlaylistsRoute: typeof StudioPlaylistsRoute
  StudioRelatoriosRoute: typeof StudioRelatoriosRoute
  StudioSenhasRoute: typeof StudioSenhasRoute
  StudioTelasRoute: typeof StudioTelasRoute
  StudioIndexRoute: typeof StudioIndexRoute
}

const StudioRouteRouteChildren: StudioRouteRouteChildren = {
  StudioAgendaRoute: StudioAgendaRoute,
  StudioConfiguracoesRoute: StudioConfiguracoesRoute,
  StudioConteudosRoute: StudioConteudosRoute,
  StudioPlaylistsRoute: StudioPlaylistsRoute,
  StudioRelatoriosRoute: StudioRelatoriosRoute,
  StudioSenhasRoute: StudioSenhasRoute,
  StudioTelasRoute: StudioTelasRoute,
  StudioIndexRoute: StudioIndexRoute,
}

const StudioRouteRouteWithChildren = StudioRouteRoute._addFileChildren(
  StudioRouteRouteChildren,
)

interface TorreRouteRouteChildren {
  TorrePlanosRoute: typeof TorrePlanosRoute
  TorreIndexRoute: typeof TorreIndexRoute
  TorreClientesOrganizationIdRoute: typeof TorreClientesOrganizationIdRoute
  TorreClientesIndexRoute: typeof TorreClientesIndexRoute
}

const TorreRouteRouteChildren: TorreRouteRouteChildren = {
  TorrePlanosRoute: TorrePlanosRoute,
  TorreIndexRoute: TorreIndexRoute,
  TorreClientesOrganizationIdRoute: TorreClientesOrganizationIdRoute,
  TorreClientesIndexRoute: TorreClientesIndexRoute,
}

const TorreRouteRouteWithChildren = TorreRouteRoute._addFileChildren(
  TorreRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StudioRouteRoute: StudioRouteRouteWithChildren,
  TorreRouteRoute: TorreRouteRouteWithChildren,
  EntrarRoute: EntrarRoute,
  SenhasRoute: SenhasRoute,
  TelaRoute: TelaRoute,
  ApiBrandingLogoRoute: ApiBrandingLogoRoute,
  ApiMediaUploadRoute: ApiMediaUploadRoute,
  ApiPublicWidgetDataRoute: ApiPublicWidgetDataRoute,
  ApiPublicPlayerEventsRoute: ApiPublicPlayerEventsRoute,
  ApiPublicPlayerPlaybackRoute: ApiPublicPlayerPlaybackRoute,
  ApiPublicPlayerRegisterRoute: ApiPublicPlayerRegisterRoute,
  ApiPublicPlayerStatusRoute: ApiPublicPlayerStatusRoute,
  ApiPublicPlayerSyncRoute: ApiPublicPlayerSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
