/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtivarRouteImport } from './routes/ativar'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as SenhasRouteImport } from './routes/senhas'
import { Route as StudioRouteRouteImport } from './routes/studio/route'
import { Route as TelaRouteImport } from './routes/tela'
import { Route as TorreRouteRouteImport } from './routes/torre/route'
import { Route as ConfirmarEmailTokenRouteImport } from './routes/confirmar-email.$token'
import { Route as EmitirIndexRouteImport } from './routes/emitir/index'
import { Route as EmitirTokenRouteImport } from './routes/emitir.$token'
import { Route as RedefinirSenhaTokenRouteImport } from './routes/redefinir-senha.$token'
import { Route as StudioIndexRouteImport } from './routes/studio/index'
import { Route as StudioAgendaRouteImport } from './routes/studio/agenda'
import { Route as StudioCadastroRouteImport } from './routes/studio/cadastro'
import { Route as StudioConfiguracoesRouteImport } from './routes/studio/configuracoes'
import { Route as StudioConteudosRouteImport } from './routes/studio/conteudos'
import { Route as StudioDownloadsRouteImport } from './routes/studio/downloads'
import { Route as StudioFaturamentoRouteImport } from './routes/studio/faturamento'
import { Route as StudioPlaylistsRouteImport } from './routes/studio/playlists'
import { Route as StudioRelatoriosRouteImport } from './routes/studio/relatorios'
import { Route as StudioSenhasRouteImport } from './routes/studio/senhas'
import { Route as StudioTerminaisRouteImport } from './routes/studio/terminais'
import { Route as StudioWidgetsRouteImport } from './routes/studio/widgets'
import { Route as TorreIndexRouteImport } from './routes/torre/index'
import { Route as TorreAplicativosRouteImport } from './routes/torre/aplicativos'
import { Route as TorreEmailRouteImport } from './routes/torre/email'
import { Route as TorreFontesRouteImport } from './routes/torre/fontes'
import { Route as TorrePagamentosRouteImport } from './routes/torre/pagamentos'
import { Route as TorrePagamentosTestesRouteImport } from './routes/torre/pagamentos-testes'
import { Route as TorrePlanosRouteImport } from './routes/torre/planos'
import { Route as TorreSiteRouteImport } from './routes/torre/site'
import { Route as TorreWidgetsRouteImport } from './routes/torre/widgets'
import { Route as ApiBrandingLogoRouteImport } from './routes/api/branding/logo'
import { Route as ApiInternalDeviceMonitorRouteImport } from './routes/api/internal/device-monitor'
import { Route as ApiMediaReplaceRouteImport } from './routes/api/media/replace'
import { Route as ApiMediaUploadRouteImport } from './routes/api/media/upload'
import { Route as ApiPublicEmissorManifestRouteImport } from './routes/api/public/emissor-manifest'
import { Route as ApiPublicWidgetDataRouteImport } from './routes/api/public/widget-data'
import { Route as ApiPublicWidgetSourcesRouteImport } from './routes/api/public/widget-sources'
import { Route as ApiQueueChimeRouteImport } from './routes/api/queue/chime'
import { Route as ApiQueueKioskMediaRouteImport } from './routes/api/queue/kiosk-media'
import { Route as ApiWidgetsBackgroundRouteImport } from './routes/api/widgets/background'
import { Route as StudioInstalarAndroidRouteImport } from './routes/studio/instalar/android'
import { Route as StudioInstalarEmissorLinuxRouteImport } from './routes/studio/instalar/emissor-linux'
import { Route as StudioInstalarEmissorWindowsRouteImport } from './routes/studio/instalar/emissor-windows'
import { Route as StudioInstalarRokuRouteImport } from './routes/studio/instalar/roku'
import { Route as StudioTerminaisDeviceIdRouteImport } from './routes/studio/terminais_.$deviceId'
import { Route as TorreClientesIndexRouteImport } from './routes/torre/clientes/index'
import { Route as TorreClientesOrganizationIdRouteImport } from './routes/torre/clientes/$organizationId'
import { Route as ApiPublicEmitterRegisterRouteImport } from './routes/api/public/emitter/register'
import { Route as ApiPublicEmitterStatusRouteImport } from './routes/api/public/emitter/status'
import { Route as ApiPublicMercadoPagoWebhookRouteImport } from './routes/api/public/mercado-pago/webhook'
import { Route as ApiPublicPlayerAnnounceRouteImport } from './routes/api/public/player/announce'
import { Route as ApiPublicPlayerChimeRouteImport } from './routes/api/public/player/chime'
import { Route as ApiPublicPlayerEventsRouteImport } from './routes/api/public/player/events'
import { Route as ApiPublicPlayerPlaybackRouteImport } from './routes/api/public/player/playback'
import { Route as ApiPublicPlayerPresenceRouteImport } from './routes/api/public/player/presence'
import { Route as ApiPublicPlayerRegisterRouteImport } from './routes/api/public/player/register'
import { Route as ApiPublicPlayerScreenshotRouteImport } from './routes/api/public/player/screenshot'
import { Route as ApiPublicPlayerStatusRouteImport } from './routes/api/public/player/status'
import { Route as ApiPublicPlayerSyncRouteImport } from './routes/api/public/player/sync'
import { Route as ApiPublicQueueCallRouteImport } from './routes/api/public/queue/call'
import { Route as ApiPublicQueueIssueRouteImport } from './routes/api/public/queue/issue'
import { Route as ApiPublicQueuePrintSpoolRouteImport } from './routes/api/public/queue/print-spool'
import { Route as StudioFaturamentoFaturaInvoiceIdRouteImport } from './routes/studio/faturamento/fatura/$invoiceId'
import { Route as StudioFaturamentoBoletoAttemptIdRouteImport } from './routes/studio/faturamento_.boleto.$attemptId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtivarRoute = AtivarRouteImport.update({
  id: '/ativar',
  path: '/ativar',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const SenhasRoute = SenhasRouteImport.update({
  id: '/senhas',
  path: '/senhas',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRouteRoute = StudioRouteRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const TelaRoute = TelaRouteImport.update({
  id: '/tela',
  path: '/tela',
  getParentRoute: () => rootRouteImport,
} as any)
const TorreRouteRoute = TorreRouteRouteImport.update({
  id: '/torre',
  path: '/torre',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmarEmailTokenRoute = ConfirmarEmailTokenRouteImport.update({
  id: '/confirmar-email/$token',
  path: '/confirmar-email/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const EmitirIndexRoute = EmitirIndexRouteImport.update({
  id: '/emitir/',
  path: '/emitir/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmitirTokenRoute = EmitirTokenRouteImport.update({
  id: '/emitir/$token',
  path: '/emitir/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaTokenRoute = RedefinirSenhaTokenRouteImport.update({
  id: '/redefinir-senha/$token',
  path: '/redefinir-senha/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRouteRoute,
} as any)
const StudioAgendaRoute = StudioAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => StudioRouteRoute,
} as any)
const StudioCadastroRoute = StudioCadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => StudioRouteRoute,
} as any)
const StudioConfiguracoesRoute = StudioConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => StudioRouteRoute,
} as any)
const StudioConteudosRoute = StudioConteudosRouteImport.update({
  id: '/conteudos',
  path: '/conteudos',
  getParentRoute: () => StudioRouteRoute,
} as any)
const StudioDownloadsRoute = StudioDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => StudioRouteRoute,
} as any)
const StudioFaturamentoRoute = StudioFaturamentoRouteImport.update({
  id: '/faturamento',
  path: '/faturamento',
  getParentRoute: () => StudioRouteRoute,
} as any)
const StudioPlaylistsRoute = StudioPlaylistsRouteImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => StudioRouteRoute,
} as any)
const StudioRelatoriosRoute = StudioRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => StudioRouteRoute,
} as any)
const StudioSenhasRoute = StudioSenhasRouteImport.update({
  id: '/senhas',
  path: '/senhas',
  getParentRoute: () => StudioRouteRoute,
} as any)
const StudioTerminaisRoute = StudioTerminaisRouteImport.update({
  id: '/terminais',
  path: '/terminais',
  getParentRoute: () => StudioRouteRoute,
} as any)
const StudioWidgetsRoute = StudioWidgetsRouteImport.update({
  id: '/widgets',
  path: '/widgets',
  getParentRoute: () => StudioRouteRoute,
} as any)
const TorreIndexRoute = TorreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TorreRouteRoute,
} as any)
const TorreAplicativosRoute = TorreAplicativosRouteImport.update({
  id: '/aplicativos',
  path: '/aplicativos',
  getParentRoute: () => TorreRouteRoute,
} as any)
const TorreEmailRoute = TorreEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => TorreRouteRoute,
} as any)
const TorreFontesRoute = TorreFontesRouteImport.update({
  id: '/fontes',
  path: '/fontes',
  getParentRoute: () => TorreRouteRoute,
} as any)
const TorrePagamentosRoute = TorrePagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => TorreRouteRoute,
} as any)
const TorrePagamentosTestesRoute = TorrePagamentosTestesRouteImport.update({
  id: '/pagamentos-testes',
  path: '/pagamentos-testes',
  getParentRoute: () => TorreRouteRoute,
} as any)
const TorrePlanosRoute = TorrePlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => TorreRouteRoute,
} as any)
const TorreSiteRoute = TorreSiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => TorreRouteRoute,
} as any)
const TorreWidgetsRoute = TorreWidgetsRouteImport.update({
  id: '/widgets',
  path: '/widgets',
  getParentRoute: () => TorreRouteRoute,
} as any)
const ApiBrandingLogoRoute = ApiBrandingLogoRouteImport.update({
  id: '/api/branding/logo',
  path: '/api/branding/logo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalDeviceMonitorRoute =
  ApiInternalDeviceMonitorRouteImport.update({
    id: '/api/internal/device-monitor',
    path: '/api/internal/device-monitor',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMediaReplaceRoute = ApiMediaReplaceRouteImport.update({
  id: '/api/media/replace',
  path: '/api/media/replace',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaUploadRoute = ApiMediaUploadRouteImport.update({
  id: '/api/media/upload',
  path: '/api/media/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEmissorManifestRoute =
  ApiPublicEmissorManifestRouteImport.update({
    id: '/api/public/emissor-manifest',
    path: '/api/public/emissor-manifest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWidgetDataRoute = ApiPublicWidgetDataRouteImport.update({
  id: '/api/public/widget-data',
  path: '/api/public/widget-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWidgetSourcesRoute = ApiPublicWidgetSourcesRouteImport.update({
  id: '/api/public/widget-sources',
  path: '/api/public/widget-sources',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQueueChimeRoute = ApiQueueChimeRouteImport.update({
  id: '/api/queue/chime',
  path: '/api/queue/chime',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQueueKioskMediaRoute = ApiQueueKioskMediaRouteImport.update({
  id: '/api/queue/kiosk-media',
  path: '/api/queue/kiosk-media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWidgetsBackgroundRoute = ApiWidgetsBackgroundRouteImport.update({
  id: '/api/widgets/background',
  path: '/api/widgets/background',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioInstalarAndroidRoute = StudioInstalarAndroidRouteImport.update({
  id: '/instalar/android',
  path: '/instalar/android',
  getParentRoute: () => StudioRouteRoute,
} as any)
const StudioInstalarEmissorLinuxRoute =
  StudioInstalarEmissorLinuxRouteImport.update({
    id: '/instalar/emissor-linux',
    path: '/instalar/emissor-linux',
    getParentRoute: () => StudioRouteRoute,
  } as any)
const StudioInstalarEmissorWindowsRoute =
  StudioInstalarEmissorWindowsRouteImport.update({
    id: '/instalar/emissor-windows',
    path: '/instalar/emissor-windows',
    getParentRoute: () => StudioRouteRoute,
  } as any)
const StudioInstalarRokuRoute = StudioInstalarRokuRouteImport.update({
  id: '/instalar/roku',
  path: '/instalar/roku',
  getParentRoute: () => StudioRouteRoute,
} as any)
const StudioTerminaisDeviceIdRoute = StudioTerminaisDeviceIdRouteImport.update({
  id: '/terminais_/$deviceId',
  path: '/terminais/$deviceId',
  getParentRoute: () => StudioRouteRoute,
} as any)
const TorreClientesIndexRoute = TorreClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => TorreRouteRoute,
} as any)
const TorreClientesOrganizationIdRoute =
  TorreClientesOrganizationIdRouteImport.update({
    id: '/clientes/$organizationId',
    path: '/clientes/$organizationId',
    getParentRoute: () => TorreRouteRoute,
  } as any)
const ApiPublicEmitterRegisterRoute =
  ApiPublicEmitterRegisterRouteImport.update({
    id: '/api/public/emitter/register',
    path: '/api/public/emitter/register',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicEmitterStatusRoute = ApiPublicEmitterStatusRouteImport.update({
  id: '/api/public/emitter/status',
  path: '/api/public/emitter/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMercadoPagoWebhookRoute =
  ApiPublicMercadoPagoWebhookRouteImport.update({
    id: '/api/public/mercado-pago/webhook',
    path: '/api/public/mercado-pago/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPlayerAnnounceRoute = ApiPublicPlayerAnnounceRouteImport.update({
  id: '/api/public/player/announce',
  path: '/api/public/player/announce',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPlayerChimeRoute = ApiPublicPlayerChimeRouteImport.update({
  id: '/api/public/player/chime',
  path: '/api/public/player/chime',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPlayerEventsRoute = ApiPublicPlayerEventsRouteImport.update({
  id: '/api/public/player/events',
  path: '/api/public/player/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPlayerPlaybackRoute = ApiPublicPlayerPlaybackRouteImport.update({
  id: '/api/public/player/playback',
  path: '/api/public/player/playback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPlayerPresenceRoute = ApiPublicPlayerPresenceRouteImport.update({
  id: '/api/public/player/presence',
  path: '/api/public/player/presence',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPlayerRegisterRoute = ApiPublicPlayerRegisterRouteImport.update({
  id: '/api/public/player/register',
  path: '/api/public/player/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPlayerScreenshotRoute =
  ApiPublicPlayerScreenshotRouteImport.update({
    id: '/api/public/player/screenshot',
    path: '/api/public/player/screenshot',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPlayerStatusRoute = ApiPublicPlayerStatusRouteImport.update({
  id: '/api/public/player/status',
  path: '/api/public/player/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPlayerSyncRoute = ApiPublicPlayerSyncRouteImport.update({
  id: '/api/public/player/sync',
  path: '/api/public/player/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicQueueCallRoute = ApiPublicQueueCallRouteImport.update({
  id: '/api/public/queue/call',
  path: '/api/public/queue/call',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicQueueIssueRoute = ApiPublicQueueIssueRouteImport.update({
  id: '/api/public/queue/issue',
  path: '/api/public/queue/issue',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicQueuePrintSpoolRoute =
  ApiPublicQueuePrintSpoolRouteImport.update({
    id: '/api/public/queue/print-spool',
    path: '/api/public/queue/print-spool',
    getParentRoute: () => rootRouteImport,
  } as any)
const StudioFaturamentoFaturaInvoiceIdRoute =
  StudioFaturamentoFaturaInvoiceIdRouteImport.update({
    id: '/fatura/$invoiceId',
    path: '/fatura/$invoiceId',
    getParentRoute: () => StudioFaturamentoRoute,
  } as any)
const StudioFaturamentoBoletoAttemptIdRoute =
  StudioFaturamentoBoletoAttemptIdRouteImport.update({
    id: '/faturamento_/boleto/$attemptId',
    path: '/faturamento/boleto/$attemptId',
    getParentRoute: () => StudioRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/studio': typeof StudioRouteRouteWithChildren
  '/torre': typeof TorreRouteRouteWithChildren
  '/ativar': typeof AtivarRoute
  '/entrar': typeof EntrarRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/senhas': typeof SenhasRoute
  '/tela': typeof TelaRoute
  '/confirmar-email/$token': typeof ConfirmarEmailTokenRoute
  '/emitir/$token': typeof EmitirTokenRoute
  '/redefinir-senha/$token': typeof RedefinirSenhaTokenRoute
  '/studio/agenda': typeof StudioAgendaRoute
  '/studio/cadastro': typeof StudioCadastroRoute
  '/studio/configuracoes': typeof StudioConfiguracoesRoute
  '/studio/conteudos': typeof StudioConteudosRoute
  '/studio/downloads': typeof StudioDownloadsRoute
  '/studio/faturamento': typeof StudioFaturamentoRouteWithChildren
  '/studio/playlists': typeof StudioPlaylistsRoute
  '/studio/relatorios': typeof StudioRelatoriosRoute
  '/studio/senhas': typeof StudioSenhasRoute
  '/studio/terminais': typeof StudioTerminaisRoute
  '/studio/widgets': typeof StudioWidgetsRoute
  '/torre/aplicativos': typeof TorreAplicativosRoute
  '/torre/email': typeof TorreEmailRoute
  '/torre/fontes': typeof TorreFontesRoute
  '/torre/pagamentos': typeof TorrePagamentosRoute
  '/torre/pagamentos-testes': typeof TorrePagamentosTestesRoute
  '/torre/planos': typeof TorrePlanosRoute
  '/torre/site': typeof TorreSiteRoute
  '/torre/widgets': typeof TorreWidgetsRoute
  '/emitir/': typeof EmitirIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/torre/': typeof TorreIndexRoute
  '/api/branding/logo': typeof ApiBrandingLogoRoute
  '/api/internal/device-monitor': typeof ApiInternalDeviceMonitorRoute
  '/api/media/replace': typeof ApiMediaReplaceRoute
  '/api/media/upload': typeof ApiMediaUploadRoute
  '/api/public/emissor-manifest': typeof ApiPublicEmissorManifestRoute
  '/api/public/widget-data': typeof ApiPublicWidgetDataRoute
  '/api/public/widget-sources': typeof ApiPublicWidgetSourcesRoute
  '/api/queue/chime': typeof ApiQueueChimeRoute
  '/api/queue/kiosk-media': typeof ApiQueueKioskMediaRoute
  '/api/widgets/background': typeof ApiWidgetsBackgroundRoute
  '/studio/instalar/android': typeof StudioInstalarAndroidRoute
  '/studio/instalar/emissor-linux': typeof StudioInstalarEmissorLinuxRoute
  '/studio/instalar/emissor-windows': typeof StudioInstalarEmissorWindowsRoute
  '/studio/instalar/roku': typeof StudioInstalarRokuRoute
  '/studio/terminais/$deviceId': typeof StudioTerminaisDeviceIdRoute
  '/torre/clientes/$organizationId': typeof TorreClientesOrganizationIdRoute
  '/torre/clientes/': typeof TorreClientesIndexRoute
  '/api/public/emitter/register': typeof ApiPublicEmitterRegisterRoute
  '/api/public/emitter/status': typeof ApiPublicEmitterStatusRoute
  '/api/public/mercado-pago/webhook': typeof ApiPublicMercadoPagoWebhookRoute
  '/api/public/player/announce': typeof ApiPublicPlayerAnnounceRoute
  '/api/public/player/chime': typeof ApiPublicPlayerChimeRoute
  '/api/public/player/events': typeof ApiPublicPlayerEventsRoute
  '/api/public/player/playback': typeof ApiPublicPlayerPlaybackRoute
  '/api/public/player/presence': typeof ApiPublicPlayerPresenceRoute
  '/api/public/player/register': typeof ApiPublicPlayerRegisterRoute
  '/api/public/player/screenshot': typeof ApiPublicPlayerScreenshotRoute
  '/api/public/player/status': typeof ApiPublicPlayerStatusRoute
  '/api/public/player/sync': typeof ApiPublicPlayerSyncRoute
  '/api/public/queue/call': typeof ApiPublicQueueCallRoute
  '/api/public/queue/issue': typeof ApiPublicQueueIssueRoute
  '/api/public/queue/print-spool': typeof ApiPublicQueuePrintSpoolRoute
  '/studio/faturamento/fatura/$invoiceId': typeof StudioFaturamentoFaturaInvoiceIdRoute
  '/studio/faturamento/boleto/$attemptId': typeof StudioFaturamentoBoletoAttemptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ativar': typeof AtivarRoute
  '/entrar': typeof EntrarRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/senhas': typeof SenhasRoute
  '/tela': typeof TelaRoute
  '/confirmar-email/$token': typeof ConfirmarEmailTokenRoute
  '/emitir/$token': typeof EmitirTokenRoute
  '/redefinir-senha/$token': typeof RedefinirSenhaTokenRoute
  '/studio/agenda': typeof StudioAgendaRoute
  '/studio/cadastro': typeof StudioCadastroRoute
  '/studio/configuracoes': typeof StudioConfiguracoesRoute
  '/studio/conteudos': typeof StudioConteudosRoute
  '/studio/downloads': typeof StudioDownloadsRoute
  '/studio/faturamento': typeof StudioFaturamentoRouteWithChildren
  '/studio/playlists': typeof StudioPlaylistsRoute
  '/studio/relatorios': typeof StudioRelatoriosRoute
  '/studio/senhas': typeof StudioSenhasRoute
  '/studio/terminais': typeof StudioTerminaisRoute
  '/studio/widgets': typeof StudioWidgetsRoute
  '/torre/aplicativos': typeof TorreAplicativosRoute
  '/torre/email': typeof TorreEmailRoute
  '/torre/fontes': typeof TorreFontesRoute
  '/torre/pagamentos': typeof TorrePagamentosRoute
  '/torre/pagamentos-testes': typeof TorrePagamentosTestesRoute
  '/torre/planos': typeof TorrePlanosRoute
  '/torre/site': typeof TorreSiteRoute
  '/torre/widgets': typeof TorreWidgetsRoute
  '/emitir': typeof EmitirIndexRoute
  '/studio': typeof StudioIndexRoute
  '/torre': typeof TorreIndexRoute
  '/api/branding/logo': typeof ApiBrandingLogoRoute
  '/api/internal/device-monitor': typeof ApiInternalDeviceMonitorRoute
  '/api/media/replace': typeof ApiMediaReplaceRoute
  '/api/media/upload': typeof ApiMediaUploadRoute
  '/api/public/emissor-manifest': typeof ApiPublicEmissorManifestRoute
  '/api/public/widget-data': typeof ApiPublicWidgetDataRoute
  '/api/public/widget-sources': typeof ApiPublicWidgetSourcesRoute
  '/api/queue/chime': typeof ApiQueueChimeRoute
  '/api/queue/kiosk-media': typeof ApiQueueKioskMediaRoute
  '/api/widgets/background': typeof ApiWidgetsBackgroundRoute
  '/studio/instalar/android': typeof StudioInstalarAndroidRoute
  '/studio/instalar/emissor-linux': typeof StudioInstalarEmissorLinuxRoute
  '/studio/instalar/emissor-windows': typeof StudioInstalarEmissorWindowsRoute
  '/studio/instalar/roku': typeof StudioInstalarRokuRoute
  '/studio/terminais/$deviceId': typeof StudioTerminaisDeviceIdRoute
  '/torre/clientes/$organizationId': typeof TorreClientesOrganizationIdRoute
  '/torre/clientes': typeof TorreClientesIndexRoute
  '/api/public/emitter/register': typeof ApiPublicEmitterRegisterRoute
  '/api/public/emitter/status': typeof ApiPublicEmitterStatusRoute
  '/api/public/mercado-pago/webhook': typeof ApiPublicMercadoPagoWebhookRoute
  '/api/public/player/announce': typeof ApiPublicPlayerAnnounceRoute
  '/api/public/player/chime': typeof ApiPublicPlayerChimeRoute
  '/api/public/player/events': typeof ApiPublicPlayerEventsRoute
  '/api/public/player/playback': typeof ApiPublicPlayerPlaybackRoute
  '/api/public/player/presence': typeof ApiPublicPlayerPresenceRoute
  '/api/public/player/register': typeof ApiPublicPlayerRegisterRoute
  '/api/public/player/screenshot': typeof ApiPublicPlayerScreenshotRoute
  '/api/public/player/status': typeof ApiPublicPlayerStatusRoute
  '/api/public/player/sync': typeof ApiPublicPlayerSyncRoute
  '/api/public/queue/call': typeof ApiPublicQueueCallRoute
  '/api/public/queue/issue': typeof ApiPublicQueueIssueRoute
  '/api/public/queue/print-spool': typeof ApiPublicQueuePrintSpoolRoute
  '/studio/faturamento/fatura/$invoiceId': typeof StudioFaturamentoFaturaInvoiceIdRoute
  '/studio/faturamento/boleto/$attemptId': typeof StudioFaturamentoBoletoAttemptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/studio': typeof StudioRouteRouteWithChildren
  '/torre': typeof TorreRouteRouteWithChildren
  '/ativar': typeof AtivarRoute
  '/entrar': typeof EntrarRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/senhas': typeof SenhasRoute
  '/tela': typeof TelaRoute
  '/confirmar-email/$token': typeof ConfirmarEmailTokenRoute
  '/emitir/$token': typeof EmitirTokenRoute
  '/redefinir-senha/$token': typeof RedefinirSenhaTokenRoute
  '/studio/agenda': typeof StudioAgendaRoute
  '/studio/cadastro': typeof StudioCadastroRoute
  '/studio/configuracoes': typeof StudioConfiguracoesRoute
  '/studio/conteudos': typeof StudioConteudosRoute
  '/studio/downloads': typeof StudioDownloadsRoute
  '/studio/faturamento': typeof StudioFaturamentoRouteWithChildren
  '/studio/playlists': typeof StudioPlaylistsRoute
  '/studio/relatorios': typeof StudioRelatoriosRoute
  '/studio/senhas': typeof StudioSenhasRoute
  '/studio/terminais': typeof StudioTerminaisRoute
  '/studio/widgets': typeof StudioWidgetsRoute
  '/torre/aplicativos': typeof TorreAplicativosRoute
  '/torre/email': typeof TorreEmailRoute
  '/torre/fontes': typeof TorreFontesRoute
  '/torre/pagamentos': typeof TorrePagamentosRoute
  '/torre/pagamentos-testes': typeof TorrePagamentosTestesRoute
  '/torre/planos': typeof TorrePlanosRoute
  '/torre/site': typeof TorreSiteRoute
  '/torre/widgets': typeof TorreWidgetsRoute
  '/emitir/': typeof EmitirIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/torre/': typeof TorreIndexRoute
  '/api/branding/logo': typeof ApiBrandingLogoRoute
  '/api/internal/device-monitor': typeof ApiInternalDeviceMonitorRoute
  '/api/media/replace': typeof ApiMediaReplaceRoute
  '/api/media/upload': typeof ApiMediaUploadRoute
  '/api/public/emissor-manifest': typeof ApiPublicEmissorManifestRoute
  '/api/public/widget-data': typeof ApiPublicWidgetDataRoute
  '/api/public/widget-sources': typeof ApiPublicWidgetSourcesRoute
  '/api/queue/chime': typeof ApiQueueChimeRoute
  '/api/queue/kiosk-media': typeof ApiQueueKioskMediaRoute
  '/api/widgets/background': typeof ApiWidgetsBackgroundRoute
  '/studio/instalar/android': typeof StudioInstalarAndroidRoute
  '/studio/instalar/emissor-linux': typeof StudioInstalarEmissorLinuxRoute
  '/studio/instalar/emissor-windows': typeof StudioInstalarEmissorWindowsRoute
  '/studio/instalar/roku': typeof StudioInstalarRokuRoute
  '/studio/terminais_/$deviceId': typeof StudioTerminaisDeviceIdRoute
  '/torre/clientes/$organizationId': typeof TorreClientesOrganizationIdRoute
  '/torre/clientes/': typeof TorreClientesIndexRoute
  '/api/public/emitter/register': typeof ApiPublicEmitterRegisterRoute
  '/api/public/emitter/status': typeof ApiPublicEmitterStatusRoute
  '/api/public/mercado-pago/webhook': typeof ApiPublicMercadoPagoWebhookRoute
  '/api/public/player/announce': typeof ApiPublicPlayerAnnounceRoute
  '/api/public/player/chime': typeof ApiPublicPlayerChimeRoute
  '/api/public/player/events': typeof ApiPublicPlayerEventsRoute
  '/api/public/player/playback': typeof ApiPublicPlayerPlaybackRoute
  '/api/public/player/presence': typeof ApiPublicPlayerPresenceRoute
  '/api/public/player/register': typeof ApiPublicPlayerRegisterRoute
  '/api/public/player/screenshot': typeof ApiPublicPlayerScreenshotRoute
  '/api/public/player/status': typeof ApiPublicPlayerStatusRoute
  '/api/public/player/sync': typeof ApiPublicPlayerSyncRoute
  '/api/public/queue/call': typeof ApiPublicQueueCallRoute
  '/api/public/queue/issue': typeof ApiPublicQueueIssueRoute
  '/api/public/queue/print-spool': typeof ApiPublicQueuePrintSpoolRoute
  '/studio/faturamento/fatura/$invoiceId': typeof StudioFaturamentoFaturaInvoiceIdRoute
  '/studio/faturamento_/boleto/$attemptId': typeof StudioFaturamentoBoletoAttemptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/studio'
    | '/torre'
    | '/ativar'
    | '/entrar'
    | '/recuperar-senha'
    | '/senhas'
    | '/tela'
    | '/confirmar-email/$token'
    | '/emitir/$token'
    | '/redefinir-senha/$token'
    | '/studio/agenda'
    | '/studio/cadastro'
    | '/studio/configuracoes'
    | '/studio/conteudos'
    | '/studio/downloads'
    | '/studio/faturamento'
    | '/studio/playlists'
    | '/studio/relatorios'
    | '/studio/senhas'
    | '/studio/terminais'
    | '/studio/widgets'
    | '/torre/aplicativos'
    | '/torre/email'
    | '/torre/fontes'
    | '/torre/pagamentos'
    | '/torre/pagamentos-testes'
    | '/torre/planos'
    | '/torre/site'
    | '/torre/widgets'
    | '/emitir/'
    | '/studio/'
    | '/torre/'
    | '/api/branding/logo'
    | '/api/internal/device-monitor'
    | '/api/media/replace'
    | '/api/media/upload'
    | '/api/public/emissor-manifest'
    | '/api/public/widget-data'
    | '/api/public/widget-sources'
    | '/api/queue/chime'
    | '/api/queue/kiosk-media'
    | '/api/widgets/background'
    | '/studio/instalar/android'
    | '/studio/instalar/emissor-linux'
    | '/studio/instalar/emissor-windows'
    | '/studio/instalar/roku'
    | '/studio/terminais/$deviceId'
    | '/torre/clientes/$organizationId'
    | '/torre/clientes/'
    | '/api/public/emitter/register'
    | '/api/public/emitter/status'
    | '/api/public/mercado-pago/webhook'
    | '/api/public/player/announce'
    | '/api/public/player/chime'
    | '/api/public/player/events'
    | '/api/public/player/playback'
    | '/api/public/player/presence'
    | '/api/public/player/register'
    | '/api/public/player/screenshot'
    | '/api/public/player/status'
    | '/api/public/player/sync'
    | '/api/public/queue/call'
    | '/api/public/queue/issue'
    | '/api/public/queue/print-spool'
    | '/studio/faturamento/fatura/$invoiceId'
    | '/studio/faturamento/boleto/$attemptId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ativar'
    | '/entrar'
    | '/recuperar-senha'
    | '/senhas'
    | '/tela'
    | '/confirmar-email/$token'
    | '/emitir/$token'
    | '/redefinir-senha/$token'
    | '/studio/agenda'
    | '/studio/cadastro'
    | '/studio/configuracoes'
    | '/studio/conteudos'
    | '/studio/downloads'
    | '/studio/faturamento'
    | '/studio/playlists'
    | '/studio/relatorios'
    | '/studio/senhas'
    | '/studio/terminais'
    | '/studio/widgets'
    | '/torre/aplicativos'
    | '/torre/email'
    | '/torre/fontes'
    | '/torre/pagamentos'
    | '/torre/pagamentos-testes'
    | '/torre/planos'
    | '/torre/site'
    | '/torre/widgets'
    | '/emitir'
    | '/studio'
    | '/torre'
    | '/api/branding/logo'
    | '/api/internal/device-monitor'
    | '/api/media/replace'
    | '/api/media/upload'
    | '/api/public/emissor-manifest'
    | '/api/public/widget-data'
    | '/api/public/widget-sources'
    | '/api/queue/chime'
    | '/api/queue/kiosk-media'
    | '/api/widgets/background'
    | '/studio/instalar/android'
    | '/studio/instalar/emissor-linux'
    | '/studio/instalar/emissor-windows'
    | '/studio/instalar/roku'
    | '/studio/terminais/$deviceId'
    | '/torre/clientes/$organizationId'
    | '/torre/clientes'
    | '/api/public/emitter/register'
    | '/api/public/emitter/status'
    | '/api/public/mercado-pago/webhook'
    | '/api/public/player/announce'
    | '/api/public/player/chime'
    | '/api/public/player/events'
    | '/api/public/player/playback'
    | '/api/public/player/presence'
    | '/api/public/player/register'
    | '/api/public/player/screenshot'
    | '/api/public/player/status'
    | '/api/public/player/sync'
    | '/api/public/queue/call'
    | '/api/public/queue/issue'
    | '/api/public/queue/print-spool'
    | '/studio/faturamento/fatura/$invoiceId'
    | '/studio/faturamento/boleto/$attemptId'
  id:
    | '__root__'
    | '/'
    | '/studio'
    | '/torre'
    | '/ativar'
    | '/entrar'
    | '/recuperar-senha'
    | '/senhas'
    | '/tela'
    | '/confirmar-email/$token'
    | '/emitir/$token'
    | '/redefinir-senha/$token'
    | '/studio/agenda'
    | '/studio/cadastro'
    | '/studio/configuracoes'
    | '/studio/conteudos'
    | '/studio/downloads'
    | '/studio/faturamento'
    | '/studio/playlists'
    | '/studio/relatorios'
    | '/studio/senhas'
    | '/studio/terminais'
    | '/studio/widgets'
    | '/torre/aplicativos'
    | '/torre/email'
    | '/torre/fontes'
    | '/torre/pagamentos'
    | '/torre/pagamentos-testes'
    | '/torre/planos'
    | '/torre/site'
    | '/torre/widgets'
    | '/emitir/'
    | '/studio/'
    | '/torre/'
    | '/api/branding/logo'
    | '/api/internal/device-monitor'
    | '/api/media/replace'
    | '/api/media/upload'
    | '/api/public/emissor-manifest'
    | '/api/public/widget-data'
    | '/api/public/widget-sources'
    | '/api/queue/chime'
    | '/api/queue/kiosk-media'
    | '/api/widgets/background'
    | '/studio/instalar/android'
    | '/studio/instalar/emissor-linux'
    | '/studio/instalar/emissor-windows'
    | '/studio/instalar/roku'
    | '/studio/terminais_/$deviceId'
    | '/torre/clientes/$organizationId'
    | '/torre/clientes/'
    | '/api/public/emitter/register'
    | '/api/public/emitter/status'
    | '/api/public/mercado-pago/webhook'
    | '/api/public/player/announce'
    | '/api/public/player/chime'
    | '/api/public/player/events'
    | '/api/public/player/playback'
    | '/api/public/player/presence'
    | '/api/public/player/register'
    | '/api/public/player/screenshot'
    | '/api/public/player/status'
    | '/api/public/player/sync'
    | '/api/public/queue/call'
    | '/api/public/queue/issue'
    | '/api/public/queue/print-spool'
    | '/studio/faturamento/fatura/$invoiceId'
    | '/studio/faturamento_/boleto/$attemptId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StudioRouteRoute: typeof StudioRouteRouteWithChildren
  TorreRouteRoute: typeof TorreRouteRouteWithChildren
  AtivarRoute: typeof AtivarRoute
  EntrarRoute: typeof EntrarRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  SenhasRoute: typeof SenhasRoute
  TelaRoute: typeof TelaRoute
  ConfirmarEmailTokenRoute: typeof ConfirmarEmailTokenRoute
  EmitirTokenRoute: typeof EmitirTokenRoute
  RedefinirSenhaTokenRoute: typeof RedefinirSenhaTokenRoute
  EmitirIndexRoute: typeof EmitirIndexRoute
  ApiBrandingLogoRoute: typeof ApiBrandingLogoRoute
  ApiInternalDeviceMonitorRoute: typeof ApiInternalDeviceMonitorRoute
  ApiMediaReplaceRoute: typeof ApiMediaReplaceRoute
  ApiMediaUploadRoute: typeof ApiMediaUploadRoute
  ApiPublicEmissorManifestRoute: typeof ApiPublicEmissorManifestRoute
  ApiPublicWidgetDataRoute: typeof ApiPublicWidgetDataRoute
  ApiPublicWidgetSourcesRoute: typeof ApiPublicWidgetSourcesRoute
  ApiQueueChimeRoute: typeof ApiQueueChimeRoute
  ApiQueueKioskMediaRoute: typeof ApiQueueKioskMediaRoute
  ApiWidgetsBackgroundRoute: typeof ApiWidgetsBackgroundRoute
  ApiPublicEmitterRegisterRoute: typeof ApiPublicEmitterRegisterRoute
  ApiPublicEmitterStatusRoute: typeof ApiPublicEmitterStatusRoute
  ApiPublicMercadoPagoWebhookRoute: typeof ApiPublicMercadoPagoWebhookRoute
  ApiPublicPlayerAnnounceRoute: typeof ApiPublicPlayerAnnounceRoute
  ApiPublicPlayerChimeRoute: typeof ApiPublicPlayerChimeRoute
  ApiPublicPlayerEventsRoute: typeof ApiPublicPlayerEventsRoute
  ApiPublicPlayerPlaybackRoute: typeof ApiPublicPlayerPlaybackRoute
  ApiPublicPlayerPresenceRoute: typeof ApiPublicPlayerPresenceRoute
  ApiPublicPlayerRegisterRoute: typeof ApiPublicPlayerRegisterRoute
  ApiPublicPlayerScreenshotRoute: typeof ApiPublicPlayerScreenshotRoute
  ApiPublicPlayerStatusRoute: typeof ApiPublicPlayerStatusRoute
  ApiPublicPlayerSyncRoute: typeof ApiPublicPlayerSyncRoute
  ApiPublicQueueCallRoute: typeof ApiPublicQueueCallRoute
  ApiPublicQueueIssueRoute: typeof ApiPublicQueueIssueRoute
  ApiPublicQueuePrintSpoolRoute: typeof ApiPublicQueuePrintSpoolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ativar': {
      id: '/ativar'
      path: '/ativar'
      fullPath: '/ativar'
      preLoaderRoute: typeof AtivarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/senhas': {
      id: '/senhas'
      path: '/senhas'
      fullPath: '/senhas'
      preLoaderRoute: typeof SenhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tela': {
      id: '/tela'
      path: '/tela'
      fullPath: '/tela'
      preLoaderRoute: typeof TelaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/torre': {
      id: '/torre'
      path: '/torre'
      fullPath: '/torre'
      preLoaderRoute: typeof TorreRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmar-email/$token': {
      id: '/confirmar-email/$token'
      path: '/confirmar-email/$token'
      fullPath: '/confirmar-email/$token'
      preLoaderRoute: typeof ConfirmarEmailTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emitir/': {
      id: '/emitir/'
      path: '/emitir'
      fullPath: '/emitir/'
      preLoaderRoute: typeof EmitirIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emitir/$token': {
      id: '/emitir/$token'
      path: '/emitir/$token'
      fullPath: '/emitir/$token'
      preLoaderRoute: typeof EmitirTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha/$token': {
      id: '/redefinir-senha/$token'
      path: '/redefinir-senha/$token'
      fullPath: '/redefinir-senha/$token'
      preLoaderRoute: typeof RedefinirSenhaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/studio/agenda': {
      id: '/studio/agenda'
      path: '/agenda'
      fullPath: '/studio/agenda'
      preLoaderRoute: typeof StudioAgendaRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/studio/cadastro': {
      id: '/studio/cadastro'
      path: '/cadastro'
      fullPath: '/studio/cadastro'
      preLoaderRoute: typeof StudioCadastroRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/studio/configuracoes': {
      id: '/studio/configuracoes'
      path: '/configuracoes'
      fullPath: '/studio/configuracoes'
      preLoaderRoute: typeof StudioConfiguracoesRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/studio/conteudos': {
      id: '/studio/conteudos'
      path: '/conteudos'
      fullPath: '/studio/conteudos'
      preLoaderRoute: typeof StudioConteudosRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/studio/downloads': {
      id: '/studio/downloads'
      path: '/downloads'
      fullPath: '/studio/downloads'
      preLoaderRoute: typeof StudioDownloadsRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/studio/faturamento': {
      id: '/studio/faturamento'
      path: '/faturamento'
      fullPath: '/studio/faturamento'
      preLoaderRoute: typeof StudioFaturamentoRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/studio/playlists': {
      id: '/studio/playlists'
      path: '/playlists'
      fullPath: '/studio/playlists'
      preLoaderRoute: typeof StudioPlaylistsRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/studio/relatorios': {
      id: '/studio/relatorios'
      path: '/relatorios'
      fullPath: '/studio/relatorios'
      preLoaderRoute: typeof StudioRelatoriosRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/studio/senhas': {
      id: '/studio/senhas'
      path: '/senhas'
      fullPath: '/studio/senhas'
      preLoaderRoute: typeof StudioSenhasRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/studio/terminais': {
      id: '/studio/terminais'
      path: '/terminais'
      fullPath: '/studio/terminais'
      preLoaderRoute: typeof StudioTerminaisRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/studio/widgets': {
      id: '/studio/widgets'
      path: '/widgets'
      fullPath: '/studio/widgets'
      preLoaderRoute: typeof StudioWidgetsRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/torre/': {
      id: '/torre/'
      path: '/'
      fullPath: '/torre/'
      preLoaderRoute: typeof TorreIndexRouteImport
      parentRoute: typeof TorreRouteRoute
    }
    '/torre/aplicativos': {
      id: '/torre/aplicativos'
      path: '/aplicativos'
      fullPath: '/torre/aplicativos'
      preLoaderRoute: typeof TorreAplicativosRouteImport
      parentRoute: typeof TorreRouteRoute
    }
    '/torre/email': {
      id: '/torre/email'
      path: '/email'
      fullPath: '/torre/email'
      preLoaderRoute: typeof TorreEmailRouteImport
      parentRoute: typeof TorreRouteRoute
    }
    '/torre/fontes': {
      id: '/torre/fontes'
      path: '/fontes'
      fullPath: '/torre/fontes'
      preLoaderRoute: typeof TorreFontesRouteImport
      parentRoute: typeof TorreRouteRoute
    }
    '/torre/pagamentos': {
      id: '/torre/pagamentos'
      path: '/pagamentos'
      fullPath: '/torre/pagamentos'
      preLoaderRoute: typeof TorrePagamentosRouteImport
      parentRoute: typeof TorreRouteRoute
    }
    '/torre/pagamentos-testes': {
      id: '/torre/pagamentos-testes'
      path: '/pagamentos-testes'
      fullPath: '/torre/pagamentos-testes'
      preLoaderRoute: typeof TorrePagamentosTestesRouteImport
      parentRoute: typeof TorreRouteRoute
    }
    '/torre/planos': {
      id: '/torre/planos'
      path: '/planos'
      fullPath: '/torre/planos'
      preLoaderRoute: typeof TorrePlanosRouteImport
      parentRoute: typeof TorreRouteRoute
    }
    '/torre/site': {
      id: '/torre/site'
      path: '/site'
      fullPath: '/torre/site'
      preLoaderRoute: typeof TorreSiteRouteImport
      parentRoute: typeof TorreRouteRoute
    }
    '/torre/widgets': {
      id: '/torre/widgets'
      path: '/widgets'
      fullPath: '/torre/widgets'
      preLoaderRoute: typeof TorreWidgetsRouteImport
      parentRoute: typeof TorreRouteRoute
    }
    '/api/branding/logo': {
      id: '/api/branding/logo'
      path: '/api/branding/logo'
      fullPath: '/api/branding/logo'
      preLoaderRoute: typeof ApiBrandingLogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/device-monitor': {
      id: '/api/internal/device-monitor'
      path: '/api/internal/device-monitor'
      fullPath: '/api/internal/device-monitor'
      preLoaderRoute: typeof ApiInternalDeviceMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/replace': {
      id: '/api/media/replace'
      path: '/api/media/replace'
      fullPath: '/api/media/replace'
      preLoaderRoute: typeof ApiMediaReplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/upload': {
      id: '/api/media/upload'
      path: '/api/media/upload'
      fullPath: '/api/media/upload'
      preLoaderRoute: typeof ApiMediaUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/emissor-manifest': {
      id: '/api/public/emissor-manifest'
      path: '/api/public/emissor-manifest'
      fullPath: '/api/public/emissor-manifest'
      preLoaderRoute: typeof ApiPublicEmissorManifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/widget-data': {
      id: '/api/public/widget-data'
      path: '/api/public/widget-data'
      fullPath: '/api/public/widget-data'
      preLoaderRoute: typeof ApiPublicWidgetDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/widget-sources': {
      id: '/api/public/widget-sources'
      path: '/api/public/widget-sources'
      fullPath: '/api/public/widget-sources'
      preLoaderRoute: typeof ApiPublicWidgetSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/queue/chime': {
      id: '/api/queue/chime'
      path: '/api/queue/chime'
      fullPath: '/api/queue/chime'
      preLoaderRoute: typeof ApiQueueChimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/queue/kiosk-media': {
      id: '/api/queue/kiosk-media'
      path: '/api/queue/kiosk-media'
      fullPath: '/api/queue/kiosk-media'
      preLoaderRoute: typeof ApiQueueKioskMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/widgets/background': {
      id: '/api/widgets/background'
      path: '/api/widgets/background'
      fullPath: '/api/widgets/background'
      preLoaderRoute: typeof ApiWidgetsBackgroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/instalar/android': {
      id: '/studio/instalar/android'
      path: '/instalar/android'
      fullPath: '/studio/instalar/android'
      preLoaderRoute: typeof StudioInstalarAndroidRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/studio/instalar/emissor-linux': {
      id: '/studio/instalar/emissor-linux'
      path: '/instalar/emissor-linux'
      fullPath: '/studio/instalar/emissor-linux'
      preLoaderRoute: typeof StudioInstalarEmissorLinuxRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/studio/instalar/emissor-windows': {
      id: '/studio/instalar/emissor-windows'
      path: '/instalar/emissor-windows'
      fullPath: '/studio/instalar/emissor-windows'
      preLoaderRoute: typeof StudioInstalarEmissorWindowsRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/studio/instalar/roku': {
      id: '/studio/instalar/roku'
      path: '/instalar/roku'
      fullPath: '/studio/instalar/roku'
      preLoaderRoute: typeof StudioInstalarRokuRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/studio/terminais_/$deviceId': {
      id: '/studio/terminais_/$deviceId'
      path: '/terminais/$deviceId'
      fullPath: '/studio/terminais/$deviceId'
      preLoaderRoute: typeof StudioTerminaisDeviceIdRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/torre/clientes/': {
      id: '/torre/clientes/'
      path: '/clientes'
      fullPath: '/torre/clientes/'
      preLoaderRoute: typeof TorreClientesIndexRouteImport
      parentRoute: typeof TorreRouteRoute
    }
    '/torre/clientes/$organizationId': {
      id: '/torre/clientes/$organizationId'
      path: '/clientes/$organizationId'
      fullPath: '/torre/clientes/$organizationId'
      preLoaderRoute: typeof TorreClientesOrganizationIdRouteImport
      parentRoute: typeof TorreRouteRoute
    }
    '/api/public/emitter/register': {
      id: '/api/public/emitter/register'
      path: '/api/public/emitter/register'
      fullPath: '/api/public/emitter/register'
      preLoaderRoute: typeof ApiPublicEmitterRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/emitter/status': {
      id: '/api/public/emitter/status'
      path: '/api/public/emitter/status'
      fullPath: '/api/public/emitter/status'
      preLoaderRoute: typeof ApiPublicEmitterStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mercado-pago/webhook': {
      id: '/api/public/mercado-pago/webhook'
      path: '/api/public/mercado-pago/webhook'
      fullPath: '/api/public/mercado-pago/webhook'
      preLoaderRoute: typeof ApiPublicMercadoPagoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/player/announce': {
      id: '/api/public/player/announce'
      path: '/api/public/player/announce'
      fullPath: '/api/public/player/announce'
      preLoaderRoute: typeof ApiPublicPlayerAnnounceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/player/chime': {
      id: '/api/public/player/chime'
      path: '/api/public/player/chime'
      fullPath: '/api/public/player/chime'
      preLoaderRoute: typeof ApiPublicPlayerChimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/player/events': {
      id: '/api/public/player/events'
      path: '/api/public/player/events'
      fullPath: '/api/public/player/events'
      preLoaderRoute: typeof ApiPublicPlayerEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/player/playback': {
      id: '/api/public/player/playback'
      path: '/api/public/player/playback'
      fullPath: '/api/public/player/playback'
      preLoaderRoute: typeof ApiPublicPlayerPlaybackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/player/presence': {
      id: '/api/public/player/presence'
      path: '/api/public/player/presence'
      fullPath: '/api/public/player/presence'
      preLoaderRoute: typeof ApiPublicPlayerPresenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/player/register': {
      id: '/api/public/player/register'
      path: '/api/public/player/register'
      fullPath: '/api/public/player/register'
      preLoaderRoute: typeof ApiPublicPlayerRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/player/screenshot': {
      id: '/api/public/player/screenshot'
      path: '/api/public/player/screenshot'
      fullPath: '/api/public/player/screenshot'
      preLoaderRoute: typeof ApiPublicPlayerScreenshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/player/status': {
      id: '/api/public/player/status'
      path: '/api/public/player/status'
      fullPath: '/api/public/player/status'
      preLoaderRoute: typeof ApiPublicPlayerStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/player/sync': {
      id: '/api/public/player/sync'
      path: '/api/public/player/sync'
      fullPath: '/api/public/player/sync'
      preLoaderRoute: typeof ApiPublicPlayerSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/queue/call': {
      id: '/api/public/queue/call'
      path: '/api/public/queue/call'
      fullPath: '/api/public/queue/call'
      preLoaderRoute: typeof ApiPublicQueueCallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/queue/issue': {
      id: '/api/public/queue/issue'
      path: '/api/public/queue/issue'
      fullPath: '/api/public/queue/issue'
      preLoaderRoute: typeof ApiPublicQueueIssueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/queue/print-spool': {
      id: '/api/public/queue/print-spool'
      path: '/api/public/queue/print-spool'
      fullPath: '/api/public/queue/print-spool'
      preLoaderRoute: typeof ApiPublicQueuePrintSpoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/faturamento/fatura/$invoiceId': {
      id: '/studio/faturamento/fatura/$invoiceId'
      path: '/fatura/$invoiceId'
      fullPath: '/studio/faturamento/fatura/$invoiceId'
      preLoaderRoute: typeof StudioFaturamentoFaturaInvoiceIdRouteImport
      parentRoute: typeof StudioFaturamentoRoute
    }
    '/studio/faturamento_/boleto/$attemptId': {
      id: '/studio/faturamento_/boleto/$attemptId'
      path: '/faturamento/boleto/$attemptId'
      fullPath: '/studio/faturamento/boleto/$attemptId'
      preLoaderRoute: typeof StudioFaturamentoBoletoAttemptIdRouteImport
      parentRoute: typeof StudioRouteRoute
    }
  }
}

interface StudioFaturamentoRouteChildren {
  StudioFaturamentoFaturaInvoiceIdRoute: typeof StudioFaturamentoFaturaInvoiceIdRoute
}

const StudioFaturamentoRouteChildren: StudioFaturamentoRouteChildren = {
  StudioFaturamentoFaturaInvoiceIdRoute: StudioFaturamentoFaturaInvoiceIdRoute,
}

const StudioFaturamentoRouteWithChildren =
  StudioFaturamentoRoute._addFileChildren(StudioFaturamentoRouteChildren)

interface StudioRouteRouteChildren {
  StudioAgendaRoute: typeof StudioAgendaRoute
  StudioCadastroRoute: typeof StudioCadastroRoute
  StudioConfiguracoesRoute: typeof StudioConfiguracoesRoute
  StudioConteudosRoute: typeof StudioConteudosRoute
  StudioDownloadsRoute: typeof StudioDownloadsRoute
  StudioFaturamentoRoute: typeof StudioFaturamentoRouteWithChildren
  StudioPlaylistsRoute: typeof StudioPlaylistsRoute
  StudioRelatoriosRoute: typeof StudioRelatoriosRoute
  StudioSenhasRoute: typeof StudioSenhasRoute
  StudioTerminaisRoute: typeof StudioTerminaisRoute
  StudioWidgetsRoute: typeof StudioWidgetsRoute
  StudioIndexRoute: typeof StudioIndexRoute
  StudioInstalarAndroidRoute: typeof StudioInstalarAndroidRoute
  StudioInstalarEmissorLinuxRoute: typeof StudioInstalarEmissorLinuxRoute
  StudioInstalarEmissorWindowsRoute: typeof StudioInstalarEmissorWindowsRoute
  StudioInstalarRokuRoute: typeof StudioInstalarRokuRoute
  StudioTerminaisDeviceIdRoute: typeof StudioTerminaisDeviceIdRoute
  StudioFaturamentoBoletoAttemptIdRoute: typeof StudioFaturamentoBoletoAttemptIdRoute
}

const StudioRouteRouteChildren: StudioRouteRouteChildren = {
  StudioAgendaRoute: StudioAgendaRoute,
  StudioCadastroRoute: StudioCadastroRoute,
  StudioConfiguracoesRoute: StudioConfiguracoesRoute,
  StudioConteudosRoute: StudioConteudosRoute,
  StudioDownloadsRoute: StudioDownloadsRoute,
  StudioFaturamentoRoute: StudioFaturamentoRouteWithChildren,
  StudioPlaylistsRoute: StudioPlaylistsRoute,
  StudioRelatoriosRoute: StudioRelatoriosRoute,
  StudioSenhasRoute: StudioSenhasRoute,
  StudioTerminaisRoute: StudioTerminaisRoute,
  StudioWidgetsRoute: StudioWidgetsRoute,
  StudioIndexRoute: StudioIndexRoute,
  StudioInstalarAndroidRoute: StudioInstalarAndroidRoute,
  StudioInstalarEmissorLinuxRoute: StudioInstalarEmissorLinuxRoute,
  StudioInstalarEmissorWindowsRoute: StudioInstalarEmissorWindowsRoute,
  StudioInstalarRokuRoute: StudioInstalarRokuRoute,
  StudioTerminaisDeviceIdRoute: StudioTerminaisDeviceIdRoute,
  StudioFaturamentoBoletoAttemptIdRoute: StudioFaturamentoBoletoAttemptIdRoute,
}

const StudioRouteRouteWithChildren = StudioRouteRoute._addFileChildren(
  StudioRouteRouteChildren,
)

interface TorreRouteRouteChildren {
  TorreAplicativosRoute: typeof TorreAplicativosRoute
  TorreEmailRoute: typeof TorreEmailRoute
  TorreFontesRoute: typeof TorreFontesRoute
  TorrePagamentosRoute: typeof TorrePagamentosRoute
  TorrePagamentosTestesRoute: typeof TorrePagamentosTestesRoute
  TorrePlanosRoute: typeof TorrePlanosRoute
  TorreSiteRoute: typeof TorreSiteRoute
  TorreWidgetsRoute: typeof TorreWidgetsRoute
  TorreIndexRoute: typeof TorreIndexRoute
  TorreClientesOrganizationIdRoute: typeof TorreClientesOrganizationIdRoute
  TorreClientesIndexRoute: typeof TorreClientesIndexRoute
}

const TorreRouteRouteChildren: TorreRouteRouteChildren = {
  TorreAplicativosRoute: TorreAplicativosRoute,
  TorreEmailRoute: TorreEmailRoute,
  TorreFontesRoute: TorreFontesRoute,
  TorrePagamentosRoute: TorrePagamentosRoute,
  TorrePagamentosTestesRoute: TorrePagamentosTestesRoute,
  TorrePlanosRoute: TorrePlanosRoute,
  TorreSiteRoute: TorreSiteRoute,
  TorreWidgetsRoute: TorreWidgetsRoute,
  TorreIndexRoute: TorreIndexRoute,
  TorreClientesOrganizationIdRoute: TorreClientesOrganizationIdRoute,
  TorreClientesIndexRoute: TorreClientesIndexRoute,
}

const TorreRouteRouteWithChildren = TorreRouteRoute._addFileChildren(
  TorreRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StudioRouteRoute: StudioRouteRouteWithChildren,
  TorreRouteRoute: TorreRouteRouteWithChildren,
  AtivarRoute: AtivarRoute,
  EntrarRoute: EntrarRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  SenhasRoute: SenhasRoute,
  TelaRoute: TelaRoute,
  ConfirmarEmailTokenRoute: ConfirmarEmailTokenRoute,
  EmitirTokenRoute: EmitirTokenRoute,
  RedefinirSenhaTokenRoute: RedefinirSenhaTokenRoute,
  EmitirIndexRoute: EmitirIndexRoute,
  ApiBrandingLogoRoute: ApiBrandingLogoRoute,
  ApiInternalDeviceMonitorRoute: ApiInternalDeviceMonitorRoute,
  ApiMediaReplaceRoute: ApiMediaReplaceRoute,
  ApiMediaUploadRoute: ApiMediaUploadRoute,
  ApiPublicEmissorManifestRoute: ApiPublicEmissorManifestRoute,
  ApiPublicWidgetDataRoute: ApiPublicWidgetDataRoute,
  ApiPublicWidgetSourcesRoute: ApiPublicWidgetSourcesRoute,
  ApiQueueChimeRoute: ApiQueueChimeRoute,
  ApiQueueKioskMediaRoute: ApiQueueKioskMediaRoute,
  ApiWidgetsBackgroundRoute: ApiWidgetsBackgroundRoute,
  ApiPublicEmitterRegisterRoute: ApiPublicEmitterRegisterRoute,
  ApiPublicEmitterStatusRoute: ApiPublicEmitterStatusRoute,
  ApiPublicMercadoPagoWebhookRoute: ApiPublicMercadoPagoWebhookRoute,
  ApiPublicPlayerAnnounceRoute: ApiPublicPlayerAnnounceRoute,
  ApiPublicPlayerChimeRoute: ApiPublicPlayerChimeRoute,
  ApiPublicPlayerEventsRoute: ApiPublicPlayerEventsRoute,
  ApiPublicPlayerPlaybackRoute: ApiPublicPlayerPlaybackRoute,
  ApiPublicPlayerPresenceRoute: ApiPublicPlayerPresenceRoute,
  ApiPublicPlayerRegisterRoute: ApiPublicPlayerRegisterRoute,
  ApiPublicPlayerScreenshotRoute: ApiPublicPlayerScreenshotRoute,
  ApiPublicPlayerStatusRoute: ApiPublicPlayerStatusRoute,
  ApiPublicPlayerSyncRoute: ApiPublicPlayerSyncRoute,
  ApiPublicQueueCallRoute: ApiPublicQueueCallRoute,
  ApiPublicQueueIssueRoute: ApiPublicQueueIssueRoute,
  ApiPublicQueuePrintSpoolRoute: ApiPublicQueuePrintSpoolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
